import { ProfileBlock, ProfileThemeConfig } from "@/types/builder";

export interface PlatformBlockTemplate {
  id: string;
  name: string;
  platform: "Instagram" | "LinkedIn" | "X (Twitter)" | "YouTube" | "TikTok" | "Spotify" | "GitHub" | "Threads" | "Luxury Atelier";
  category: "Profile Cards" | "Premium Posts & Content" | "Shop & Affiliates" | "Inquiry & Booking" | "VIP & Community";
  description: string;
  badge: string;
  badgeColor: string;
  stats?: string;
  tags?: string[];
  interactiveType?: "code_copy" | "media" | "form" | "grid" | "locked" | "qr" | "social";
  block: ProfileBlock;
}

export const REAL_BLOCK_TEMPLATES: PlatformBlockTemplate[] = [
  // ==========================================
  // 1. PROFILE CARDS & SOCIAL PRESENCE BLOCKS
  // ==========================================
  {
    id: "blk-prof-instagram",
    name: "Instagram Official Profile & Reels Card",
    platform: "Instagram",
    category: "Profile Cards",
    description: "Verified Instagram profile badge block displaying official handle, follower call-to-action, and photo thumbnail.",
    badge: "Instagram Profile",
    badgeColor: "bg-gradient-to-r from-pink-500 via-purple-500 to-amber-500 text-white",
    block: {
      id: "template-block-prof-instagram",
      type: "featured_link",
      position: 0,
      title: "Instagram: @camille_styles (185k Followers)",
      subtitle: "Daily fashion carousels, Paris week vlogs, styling GRWM reels & stories",
      isVisible: true,
      isArchived: false,
      url: "https://instagram.com",
      badgeText: "VERIFIED CREATOR",
      highlightCoverUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
      callToAction: "Follow on Instagram",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-prof-x",
    name: "X (Twitter) Builder & Founder Profile Card",
    platform: "X (Twitter)",
    category: "Profile Cards",
    description: "Showcases live posts on X, autonomous tech threads, build-in-public metrics, and follow link.",
    badge: "X (Twitter) Profile",
    badgeColor: "bg-black text-white border border-neutral-700",
    block: {
      id: "template-block-prof-x",
      type: "featured_link",
      position: 0,
      title: "X: @alex_builds ⚡ (YC W26 Founder)",
      subtitle: "Shipping autonomous AI agents in public • Daily technical threads & MRR updates",
      isVisible: true,
      isArchived: false,
      url: "https://x.com",
      badgeText: "BUILDING IN PUBLIC",
      highlightCoverUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
      callToAction: "Follow on X / DMs Open",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-prof-linkedin",
    name: "LinkedIn Executive & Thought Leader Card",
    platform: "LinkedIn",
    category: "Profile Cards",
    description: "Executive badge highlighting Top Voice status, venture advisory, and weekly long-form essays.",
    badge: "LinkedIn Profile",
    badgeColor: "bg-[#0A66C2] text-white",
    block: {
      id: "template-block-prof-linkedin",
      type: "featured_link",
      position: 0,
      title: "LinkedIn: Marcus Vance (Top Voice in AI)",
      subtitle: "Managing Partner @ApexVentures • Enterprise scale & board governance insights for 120k+ readers",
      isVisible: true,
      isArchived: false,
      url: "https://linkedin.com",
      badgeText: "TOP VOICE 2026",
      highlightCoverUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
      callToAction: "Connect on LinkedIn",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-prof-socials-all",
    name: "Complete Multi-Platform Creator Social Hub",
    platform: "Instagram",
    category: "Profile Cards",
    description: "Clean golden icon bar linking your Instagram, TikTok, YouTube, X, LinkedIn, and email in one touch.",
    badge: "All Socials",
    badgeColor: "bg-[#D4AF37] text-[#1A1C20] font-bold",
    block: {
      id: "template-block-prof-socials-all",
      type: "social_icons",
      position: 0,
      title: "Official Verified Channels",
      isVisible: true,
      isArchived: false,
      iconStyle: "filled_gold",
      platformLinks: [
        { platform: "instagram", url: "https://instagram.com", position: 0 },
        { platform: "x", url: "https://x.com", position: 1 },
        { platform: "linkedin", url: "https://linkedin.com", position: 2 },
        { platform: "youtube", url: "https://youtube.com", position: 3 },
        { platform: "tiktok", url: "https://tiktok.com", position: 4 },
        { platform: "email", url: "mailto:creator@asoobi.com", position: 5 },
      ],
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },

  // ==========================================
  // 2. PREMIUM POSTS & EXCLUSIVE CONTENT BLOCKS
  // ==========================================
  {
    id: "blk-prem-x-thread",
    name: "X (Twitter) Viral Masterclass Thread",
    platform: "X (Twitter)",
    category: "Premium Posts & Content",
    description: "Featured breakdown post showcasing your highest-performing viral thread on architecture, growth, or tech.",
    badge: "X Viral Thread",
    badgeColor: "bg-black text-[#00F0FF] border border-neutral-700",
    block: {
      id: "template-block-prem-x-thread",
      type: "standard_link",
      position: 0,
      title: "Viral Breakdown: How We Scaled Autonomous AI to 5M Requests",
      subtitle: "32-tweet deep dive into caching, token optimization, and edge inference (1.4M views on X)",
      isVisible: true,
      isArchived: false,
      url: "https://x.com",
      thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=200&q=80",
      openInNewTab: true,
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-prem-instagram-post",
    name: "Instagram Editorial Lookbook Post",
    platform: "Instagram",
    category: "Premium Posts & Content",
    description: "Rich visual cover banner showcasing your top Instagram carousel photoshoot with behind-the-scenes access.",
    badge: "Instagram Reel",
    badgeColor: "bg-pink-600 text-white",
    block: {
      id: "template-block-prem-instagram-post",
      type: "featured_link",
      position: 0,
      title: "Vogue Paris Feature: Spring Haute Couture Gallery",
      subtitle: "Behind-the-scenes runway photography, moodboard sketches & high-res editorial stills.",
      isVisible: true,
      isArchived: false,
      url: "https://instagram.com",
      badgeText: "VIRAL EDIT",
      highlightCoverUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80",
      callToAction: "View Full Instagram Reel & Photos",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-prem-locked-case-study",
    name: "VIP Members Only: Private Case Study (Password)",
    platform: "LinkedIn",
    category: "Premium Posts & Content",
    description: "Password-gated confidential research dossier and enterprise architecture audit for paying clients.",
    badge: "VIP Premium Content",
    badgeColor: "bg-purple-900 text-purple-200 border border-purple-500",
    block: {
      id: "template-block-prem-locked-case-study",
      type: "standard_link",
      position: 0,
      title: "Confidential: $120M Enterprise AI Transition Playbook",
      subtitle: "Full breakdown of tech stack, contracts & governance models (Password: VIP_INSIDER)",
      isVisible: true,
      isArchived: false,
      url: "https://asoobi.com/premium/ai-playbook",
      thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=200&q=80",
      openInNewTab: true,
      accessRules: {
        isLocked: true,
        password: "VIP_INSIDER",
        scheduleEnabled: false,
      },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-prem-youtube-film",
    name: "YouTube 4K Documentary Premiere Post",
    platform: "YouTube",
    category: "Premium Posts & Content",
    description: "Cinematic full-width film banner directing audience to your latest high-production 4K video.",
    badge: "YouTube 4K",
    badgeColor: "bg-[#FF0000] text-white",
    block: {
      id: "template-block-prem-youtube-film",
      type: "featured_link",
      position: 0,
      title: "Documentary Film: Tokyo After Hours (4K HDR)",
      subtitle: "18-minute cinematic journey through hidden sound listening bars & minimalist architecture.",
      isVisible: true,
      isArchived: false,
      url: "https://youtube.com",
      badgeText: "PREMIERE",
      highlightCoverUrl: "https://images.unsplash.com/photo-1518173946687-a4c8a383392e?auto=format&fit=crop&w=800&q=80",
      callToAction: "Watch Film on YouTube",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-prem-substack-essay",
    name: "LinkedIn / Substack Longform Essay",
    platform: "LinkedIn",
    category: "Premium Posts & Content",
    description: "High-engagement essay post linking to your executive Substack memo or LinkedIn newsletter.",
    badge: "Substack Essay",
    badgeColor: "bg-[#FF6719] text-white",
    block: {
      id: "template-block-prem-substack-essay",
      type: "standard_link",
      position: 0,
      title: "Essay #42: The Death of the 10x Developer in the Agent Era",
      subtitle: "Why judgment and domain context are eclipsing raw syntax typing in 2026.",
      isVisible: true,
      isArchived: false,
      url: "https://substack.com",
      thumbnailUrl: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=200&q=80",
      openInNewTab: true,
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },

  // ==========================================
  // 3. SHOPPING & AFFILIATES BLOCKS
  // ==========================================
  {
    id: "blk-ig-outfits",
    name: "Instagram Weekly Outfits & ShopMy Shelf",
    platform: "Instagram",
    category: "Shop & Affiliates",
    description: "Grid collection of current season outfit essentials with direct shopping links and prices.",
    badge: "Instagram Shop",
    badgeColor: "bg-pink-600 text-white",
    block: {
      id: "template-block-ig-outfits",
      type: "collection",
      position: 0,
      title: "Shop My Instagram Outfits (LTK & ShopMy)",
      subtitle: "Tap to shop exact pieces I wore this week",
      isVisible: true,
      isArchived: false,
      layout: "grid",
      accessRules: { isLocked: false, scheduleEnabled: false },
      items: [
        {
          id: "item-ig-1",
          title: "Oversized Cashmere Knit",
          url: "https://instagram.com",
          price: "$290",
          thumbnailUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=300&q=80",
        },
        {
          id: "item-ig-2",
          title: "Vintage Leather Tote",
          url: "https://instagram.com",
          price: "$480",
          thumbnailUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=300&q=80",
        },
        {
          id: "item-ig-3",
          title: "Signature Gold Signet Ring",
          url: "https://instagram.com",
          price: "$145",
          thumbnailUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=300&q=80",
        },
      ],
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-tt-amazon",
    name: "TikTok Amazon Storefront Viral Finds",
    platform: "TikTok",
    category: "Shop & Affiliates",
    description: "Product grid showcase highlighting viral items tested in your short videos with price tags.",
    badge: "TikTok Storefront",
    badgeColor: "bg-[#FF9900] text-black font-semibold",
    block: {
      id: "template-block-tt-amazon",
      type: "collection",
      position: 0,
      title: "My Viral TikTok Finds (Amazon Storefront)",
      subtitle: "All the viral home, skincare, and studio tech from my recent videos",
      isVisible: true,
      isArchived: false,
      layout: "grid",
      accessRules: { isLocked: false, scheduleEnabled: false },
      items: [
        {
          id: "item-tt-1",
          title: "RGB Sunset Aura Lamp",
          url: "https://amazon.com",
          price: "$34",
          thumbnailUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=300&q=80",
        },
        {
          id: "item-tt-2",
          title: "Wireless Lavalier Mic Pro",
          url: "https://amazon.com",
          price: "$79",
          thumbnailUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=300&q=80",
        },
        {
          id: "item-tt-3",
          title: "Hydra Glass Skin Serum",
          url: "https://amazon.com",
          price: "$28",
          thumbnailUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=300&q=80",
        },
      ],
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-ig-presets",
    name: "Instagram Lightroom Presets Discount Coupon",
    platform: "Instagram",
    category: "Shop & Affiliates",
    description: "One-click copy promo code block for creator filters, digital downloads, and courses.",
    badge: "Instagram Promo",
    badgeColor: "bg-rose-500 text-white",
    block: {
      id: "template-block-ig-presets",
      type: "discount_code",
      position: 0,
      title: "Lightroom Aesthetic Presets 2026",
      subtitle: "Get 25% off my 1-click Paris & Milan photo presets",
      isVisible: true,
      isArchived: false,
      code: "CAMILLE25",
      discountPercentageOrValue: "25% OFF",
      brandName: "Camille Preset Shop",
      destinationUrl: "https://instagram.com",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-x-coupon",
    name: "X (Twitter) SaaS Early Bird Discount Code",
    platform: "X (Twitter)",
    category: "Shop & Affiliates",
    description: "Exclusive lifetime coupon code for X/Twitter followers building in public.",
    badge: "X Early Bird",
    badgeColor: "bg-neutral-800 text-[#00F0FF]",
    block: {
      id: "template-block-x-coupon",
      type: "discount_code",
      position: 0,
      title: "Founder Community Lifetime Pass",
      subtitle: "Special 40% discount code for our X / Twitter followers only",
      isVisible: true,
      isArchived: false,
      code: "BUILDINPUBLIC",
      discountPercentageOrValue: "40% OFF",
      brandName: "HyperScale Pro Tier",
      destinationUrl: "https://hyperscale.ai",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },

  // ==========================================
  // 4. INQUIRY, SPONSORSHIP & BOOKING FORMS
  // ==========================================
  {
    id: "blk-ig-collab",
    name: "Instagram Brand Sponsorship & Collab Form",
    platform: "Instagram",
    category: "Inquiry & Booking",
    description: "Tailored brand inquiry form for agencies and PR reps with format selection (Reels, Carousels, Stories).",
    badge: "Instagram PR",
    badgeColor: "bg-purple-600 text-white",
    block: {
      id: "template-block-ig-collab",
      type: "contact_form",
      position: 0,
      title: "Brand Sponsorships & PR Inquiries",
      subtitle: "Direct line for agencies, press pulls, and brand partnerships",
      isVisible: true,
      isArchived: false,
      targetEmail: "collaborations@camillelaurent.com",
      fields: {
        collectName: true,
        collectPhone: false,
        collectNote: true,
      },
      customFields: [
        { id: "brand_name", label: "Brand Name", type: "text", placeholder: "e.g. Chanel / Celine / Jacquemus", required: true },
        { id: "deliverables", label: "Campaign Format", type: "select", options: ["Instagram Reel + 3 Stories", "Dedicated Photo Carousel", "YouTube Integration", "Long-term Ambassadorship"], required: true },
        { id: "budget_range", label: "Target Campaign Budget", type: "select", options: ["$3,000 - $7,500", "$7,500 - $20,000", "$20,000 - $50,000+", "Product Gifting / Seeding"], required: true },
      ],
      successMessage: "Thank you! Camille's management agency will review your brief within 24 hours.",
      submitButtonText: "Submit Collaboration Pitch",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-li-keynote",
    name: "LinkedIn Keynote & Executive Speaking Form",
    platform: "LinkedIn",
    category: "Inquiry & Booking",
    description: "Professional inquiry form for conference organizers, executive retreats, and board summits.",
    badge: "LinkedIn Speaker",
    badgeColor: "bg-[#0A66C2] text-white",
    block: {
      id: "template-block-li-keynote",
      type: "contact_form",
      position: 0,
      title: "Keynote Speaking & Advisory Inquiries",
      subtitle: "Inquire for global summits, executive retreats & corporate keynotes",
      isVisible: true,
      isArchived: false,
      targetEmail: "speaking@marcusvance.com",
      fields: {
        collectName: true,
        collectPhone: true,
        collectNote: true,
      },
      customFields: [
        { id: "event_name", label: "Conference / Organization Name", type: "text", placeholder: "e.g. World Economic Forum / SaaStr", required: true },
        { id: "event_date", label: "Event Target Date", type: "date", required: true },
        { id: "format", label: "Format", type: "select", options: ["In-Person Keynote (45 min)", "Panel Fireside Chat", "Executive Offsite Workshop", "Virtual Global Townhall"], required: true },
      ],
      successMessage: "Inquiry received. Marcus's chief of staff will confirm availability within 24 hours.",
      submitButtonText: "Check Speaking Availability",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-x-investor",
    name: "X (Twitter) Angel & Investor DocSend Pitch Form",
    platform: "X (Twitter)",
    category: "Inquiry & Booking",
    description: "Streamlined pitch deck request form with ticket size selection used by founders on X.",
    badge: "X Founder Pitch",
    badgeColor: "bg-black text-white border border-neutral-700",
    block: {
      id: "template-block-x-investor",
      type: "contact_form",
      position: 0,
      title: "Angel Investment & Strategic Advisory Pitch",
      subtitle: "Currently opening our Seed extension round. Inquire for our investor deck.",
      isVisible: true,
      isArchived: false,
      targetEmail: "founders@hyperscale.ai",
      fields: {
        collectName: true,
        collectPhone: false,
        collectNote: true,
      },
      customFields: [
        { id: "fund_name", label: "Fund / Angel Name", type: "text", placeholder: "e.g. Andreessen / Sequoia / Scout", required: true },
        { id: "check_size", label: "Target Ticket Size", type: "select", options: ["$25k - $50k (Angel)", "$100k - $250k", "$500k+ (Lead / Syndicate)"], required: true },
      ],
      successMessage: "Deck request sent. Alex will reply with DocSend link within 12 hours.",
      submitButtonText: "Request Investor Deck",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-yt-sponsors",
    name: "YouTube Dedicated Video Sponsor Inquiries",
    platform: "YouTube",
    category: "Inquiry & Booking",
    description: "Professional YouTube creator sponsor booking form with mid-roll, title sponsor, and bundle options.",
    badge: "YouTube Sponsor",
    badgeColor: "bg-[#FF0000] text-white",
    block: {
      id: "template-block-yt-sponsors",
      type: "contact_form",
      position: 0,
      title: "Channel Sponsorships & Product Integrations",
      subtitle: "Dedicated 60-90s integrations, dedicated reviews, and long-term channel partnerships",
      isVisible: true,
      isArchived: false,
      targetEmail: "sponsors@kaisterling.com",
      fields: {
        collectName: true,
        collectPhone: false,
        collectNote: true,
      },
      customFields: [
        { id: "sponsor_brand", label: "Brand / Product Name", type: "text", placeholder: "e.g. Sony / Apple / Shure", required: true },
        { id: "slot_type", label: "Integration Tier", type: "select", options: ["Dedicated 60s Mid-Roll", "Integrated Video Title Sponsor", "3-Video Campaign Bundle", "Full Dedicated Review Video"], required: true },
      ],
      successMessage: "Thank you. Our channel production director will send our 2026 rate card and media kit.",
      submitButtonText: "Submit Sponsor Brief",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-tt-ugc",
    name: "TikTok 48-Hour UGC Package Booking Form",
    platform: "TikTok",
    category: "Inquiry & Booking",
    description: "Fast-turnaround UGC commercial pitch form used by TikTok creators and video strategists.",
    badge: "TikTok UGC",
    badgeColor: "bg-black text-[#00F2FE] border border-[#FE2C55]",
    block: {
      id: "template-block-tt-ugc",
      type: "contact_form",
      position: 0,
      title: "Book UGC Video Package",
      subtitle: "Fast 48-hour turnarounds for high-converting TikTok Ad hooks & organic UGC",
      isVisible: true,
      isArchived: false,
      targetEmail: "booking@chenmedia.co",
      fields: {
        collectName: true,
        collectPhone: false,
        collectNote: true,
      },
      customFields: [
        { id: "brand_handle", label: "Brand Handle / URL", type: "text", placeholder: "@brandname on TikTok", required: true },
        { id: "package_type", label: "Desired Video Package", type: "select", options: ["3x UGC Ad Hooks Bundle", "5x UGC TikTok Variations", "Spark Ads Whitelisting Rights", "Monthly Retainer (10 videos)"], required: true },
      ],
      successMessage: "Thanks! Mia will send contract, onboarding link & product shipping address.",
      submitButtonText: "Request UGC Rate Card",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-lux-concierge",
    name: "Luxury Atelier Private Salon & Concierge Form",
    platform: "Luxury Atelier",
    category: "Inquiry & Booking",
    description: "High-end bespoke consultation form with suite location (Paris, Tokyo, London, NYC) and acquisition intent.",
    badge: "Luxury Concierge",
    badgeColor: "bg-[#D4AF37] text-[#1A1C20] font-bold",
    block: {
      id: "template-block-lux-concierge",
      type: "contact_form",
      position: 0,
      title: "Private Salon Appointment & Commissions",
      subtitle: "Book a confidential consultation at our Paris atelier or private global suite",
      isVisible: true,
      isArchived: false,
      targetEmail: "concierge@maisonsolenne.com",
      fields: {
        collectName: true,
        collectPhone: true,
        collectNote: true,
      },
      customFields: [
        { id: "city_suite", label: "Preferred Atelier Location", type: "select", options: ["Place Vendôme (Paris)", "Bond Street (London)", "Ginza (Tokyo)", "Fifth Avenue (New York)", "Private Flying Concierge"], required: true },
        { id: "bespoke_intent", label: "Acquisition Interest", type: "select", options: ["Custom Bespoke Commission", "Private Collection Viewing", "Archival Piece Restoration", "Red Carpet Loan Inquiries"], required: true },
      ],
      successMessage: "Thank you. Our private client liaison will arrange your salon appointment directly.",
      submitButtonText: "Request Private Appointment",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },

  // ==========================================
  // 5. VIP PASSES & COMMUNITIES
  // ==========================================
  {
    id: "blk-x-discord",
    name: "X (Twitter) Discord Community Invite",
    platform: "X (Twitter)",
    category: "VIP & Community",
    description: "Direct community link for developer communities, open-source projects, and beta testers.",
    badge: "X Community",
    badgeColor: "bg-[#5865F2] text-white",
    block: {
      id: "template-block-x-discord",
      type: "standard_link",
      position: 0,
      title: "Join 14,000+ AI Builders on Discord",
      subtitle: "Direct feedback channel, open-source models, and daily changelog drops.",
      isVisible: true,
      isArchived: false,
      url: "https://discord.com",
      thumbnailUrl: "https://images.unsplash.com/photo-1614680376593-902f749f7ffc?auto=format&fit=crop&w=200&q=80",
      openInNewTab: true,
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-lux-pass",
    name: "Luxury Password-Locked VIP Trunk Show Pass",
    platform: "Luxury Atelier",
    category: "VIP & Community",
    description: "Password-protected link for private collectors, haute couture clients, and invitation-only trunk shows.",
    badge: "Luxury VIP Pass",
    badgeColor: "bg-amber-900 text-amber-200",
    block: {
      id: "template-block-lux-pass",
      type: "standard_link",
      position: 0,
      title: "VIP Backstage Salon Pass (Paris Haute Couture)",
      subtitle: "Private salon guestlist link (Password: VENDOME_VIP)",
      isVisible: true,
      isArchived: false,
      url: "https://asoobi.com/vip/salon",
      icon: "Lock",
      openInNewTab: true,
      accessRules: {
        isLocked: true,
        password: "VENDOME_VIP",
        scheduleEnabled: false,
      },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-prof-spotify",
    name: "Spotify Verified Artist & Top Stream Spotlight",
    platform: "Spotify",
    category: "Profile Cards",
    description: "Official Spotify discography card showcasing your latest single or album release with listener metrics.",
    badge: "Spotify Artist",
    badgeColor: "bg-[#1ED760] text-black font-semibold",
    stats: "2.4M Monthly",
    tags: ["Music", "Audio", "Streaming", "Verified"],
    interactiveType: "media",
    block: {
      id: "template-block-prof-spotify",
      type: "featured_link",
      position: 0,
      title: "Spotify: Neon Echoes (2.4M Monthly Listeners)",
      subtitle: "New EP 'Velvet Horizon' out now • Stream on Spotify, Apple Music & TIDAL",
      isVisible: true,
      isArchived: false,
      url: "https://spotify.com",
      badgeText: "NEW EP OUT NOW",
      highlightCoverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
      callToAction: "Listen on Spotify",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-prof-github",
    name: "GitHub Developer & OSS Engineer Card",
    platform: "GitHub",
    category: "Profile Cards",
    description: "Developer profile showcase highlighting open source repositories, GitHub stars, and live code demos.",
    badge: "GitHub OSS",
    badgeColor: "bg-[#24292F] text-white border border-neutral-700",
    stats: "4.8k Stars",
    tags: ["Developer", "Open Source", "Code", "Engineering"],
    interactiveType: "media",
    block: {
      id: "template-block-prof-github",
      type: "featured_link",
      position: 0,
      title: "GitHub: @dev_zen (4.8k Stars • 120 Repos)",
      subtitle: "Creator of NextAgent.js & WebGPU micro-kernels • Star repositories & contribute",
      isVisible: true,
      isArchived: false,
      url: "https://github.com",
      badgeText: "OPEN SOURCE",
      highlightCoverUrl: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&fit=crop&w=800&q=80",
      callToAction: "View Repositories & Star on GitHub",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-prof-threads",
    name: "Threads by Meta Creator Profile Card",
    platform: "Threads",
    category: "Profile Cards",
    description: "Connect your Instagram Threads feed for daily thoughts, design critique, and conversational micro-posts.",
    badge: "Threads Meta",
    badgeColor: "bg-black text-white border border-neutral-800",
    stats: "42k Members",
    tags: ["Social", "Meta", "Conversations", "Community"],
    interactiveType: "media",
    block: {
      id: "template-block-prof-threads",
      type: "featured_link",
      position: 0,
      title: "Threads: @sophia.design (42k Active)",
      subtitle: "Unfiltered design critique, UI motion experiments & founder thoughts everyday",
      isVisible: true,
      isArchived: false,
      url: "https://threads.net",
      badgeText: "DAILY THREADS",
      highlightCoverUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
      callToAction: "Follow on Threads",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-prem-podcast",
    name: "Apple Podcasts & Spotify Masterclass Episode",
    platform: "Spotify",
    category: "Premium Posts & Content",
    description: "Featured audio episode card showcasing guest interviews, timestamps, and streaming links.",
    badge: "Top 10 Podcast",
    badgeColor: "bg-gradient-to-r from-purple-600 to-indigo-600 text-white",
    stats: "45 Min • Ep #88",
    tags: ["Podcast", "Audio", "Interview", "Knowledge"],
    interactiveType: "media",
    block: {
      id: "template-block-prem-podcast",
      type: "featured_link",
      position: 0,
      title: "Podcast Ep #88: The Next Trillion Dollar Interface",
      subtitle: "Featuring Jony Ive design alumnus on spatial computing, ambient haptics & AI agency",
      isVisible: true,
      isArchived: false,
      url: "https://open.spotify.com",
      badgeText: "HOT EPISODE",
      highlightCoverUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=800&q=80",
      callToAction: "Listen to Episode (45m)",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-shop-capsule",
    name: "Limited Edition Capsule Drop & Merch Grid",
    platform: "Luxury Atelier",
    category: "Shop & Affiliates",
    description: "Curated shopping grid with high-res product photos, price tags, and direct checkout links.",
    badge: "Exclusive Drop",
    badgeColor: "bg-[#D4AF37] text-black font-bold",
    stats: "3 Items • Drop Live",
    tags: ["Ecommerce", "Fashion", "Limited", "Merch"],
    interactiveType: "grid",
    block: {
      id: "template-block-shop-capsule",
      type: "collection",
      position: 0,
      title: "Autumn Capsule: Heavyweight Minimalist Collection",
      subtitle: "Hand-numbered 380gsm organic French terry garments • Free worldwide shipping",
      isVisible: true,
      isArchived: false,
      layout: "grid",
      accessRules: { isLocked: false, scheduleEnabled: false },
      items: [
        {
          id: "capsule-item-1",
          title: "Raw Onyx Hoodie (No Strings)",
          url: "https://asoobi.com/shop/hoodie",
          price: "$180",
          thumbnailUrl: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=300&q=80",
        },
        {
          id: "capsule-item-2",
          title: "Minimalist Structured Tote",
          url: "https://asoobi.com/shop/tote",
          price: "$240",
          thumbnailUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=300&q=80",
        },
        {
          id: "capsule-item-3",
          title: "Brushed Brass Keychain",
          url: "https://asoobi.com/shop/keychain",
          price: "$65",
          thumbnailUrl: "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=300&q=80",
        },
      ],
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-form-advisory",
    name: "1:1 Executive Strategy Advisory Session",
    platform: "LinkedIn",
    category: "Inquiry & Booking",
    description: "Interactive booking inquiry for founders and executives seeking 1:1 roadmap reviews.",
    badge: "1:1 Advisory",
    badgeColor: "bg-emerald-600 text-white",
    stats: "$1,500/hr • 3 Slots Left",
    tags: ["Consulting", "Executive", "Strategy", "Booking"],
    interactiveType: "form",
    block: {
      id: "template-block-form-advisory",
      type: "contact_form",
      position: 0,
      title: "Book 1:1 Executive Advisory Session",
      subtitle: "Direct strategy consultation for venture-backed founders and product leaders",
      isVisible: true,
      isArchived: false,
      targetEmail: "advisory@marcusvance.com",
      fields: {
        collectName: true,
        collectPhone: true,
        collectNote: true,
      },
      customFields: [
        { id: "company_stage", label: "Company Stage", type: "select", options: ["Series A / B ($5M - $25M)", "Seed / Pre-seed", "Growth / Enterprise ($50M+)", "Individual Angel Investor"], required: true },
        { id: "strategic_focus", label: "Primary Objective", type: "select", options: ["AI Product Roadmap Review", "Fundraising & Pitch Deck Prep", "GTM & Enterprise Expansion", "Board & Leadership Coaching"], required: true },
        { id: "target_month", label: "Target Session Timeline", type: "select", options: ["Urgent (Within 7 days)", "This Month", "Next Quarter"], required: true },
      ],
      successMessage: "Advisory request received! Marcus's team will email available calendar slots within 12 hours.",
      submitButtonText: "Request Advisory Slot",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-qr-connect-instant",
    name: "Instant In-Person QR Code Connect Badge",
    platform: "Luxury Atelier",
    category: "VIP & Community",
    description: "High-contrast golden QR code block ideal for networking events, business cards, and meetups.",
    badge: "Instant Scan",
    badgeColor: "bg-[#D4AF37] text-black font-bold",
    stats: "Vector SVG QR",
    tags: ["Networking", "QR Code", "In-Person", "Contact"],
    interactiveType: "qr",
    block: {
      id: "template-block-qr-connect-instant",
      type: "qr_code",
      position: 0,
      title: "Scan to Connect & Save Contact (vCard)",
      subtitle: "Point your smartphone camera to save full contact info & portfolio instantly",
      targetUrl: "https://asoobi.com/camille",
      downloadLabel: "Download High-Res QR vCard",
      isVisible: true,
      isArchived: false,
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
  {
    id: "blk-vip-telegram",
    name: "Telegram Private Alpha & Inner Circle Club",
    platform: "X (Twitter)",
    category: "VIP & Community",
    description: "Exclusive private community channel for breaking alerts, dealflow, and private chats.",
    badge: "Telegram Alpha",
    badgeColor: "bg-[#229ED9] text-white",
    stats: "Inner Circle Only",
    tags: ["Community", "Alpha", "Crypto", "Tech"],
    interactiveType: "locked",
    block: {
      id: "template-block-vip-telegram",
      type: "standard_link",
      position: 0,
      title: "Private Alpha Channel (Telegram Group)",
      subtitle: "Unreleased venture deal memos, market research & direct founder group chat",
      isVisible: true,
      isArchived: false,
      url: "https://t.me/asoobi_alpha",
      thumbnailUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=200&q=80",
      openInNewTab: true,
      accessRules: {
        isLocked: true,
        password: "ALPHA_MEMBERS",
        scheduleEnabled: false,
      },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  },
];

// Curated themes extracted for the Themes & Styling section - Top 9 Best Combinations
export const CURATED_PLATFORM_THEMES: ProfileThemeConfig[] = [
  {
    id: "asoobi_luxury_gold",
    name: "Asoobi Signature Gold",
    palette: {
      background: "#F9F9F7",
      cardBackground: "#FFFFFF",
      primaryText: "#1A1C20",
      secondaryText: "#918355",
      accentGold: "#D4AF37",
      border: "#E5E0D2",
      buttonBackground: "#D4AF37",
      buttonText: "#1A1C20",
    },
    typography: {
      headingFont: "Playfair Display",
      bodyFont: "Inter",
    },
    geometry: {
      buttonRadius: "rounded-xl",
      cardRadius: "rounded-2xl",
      buttonStyle: "shadow_gold",
    },
    backgroundConfig: {
      type: "canvas_constellation",
      patternColor: "#D4AF37",
      patternOpacity: 0.75,
      particleSpeed: 1,
    },
  },
  {
    id: "obsidian_noir",
    name: "Obsidian Noir",
    palette: {
      background: "#0A0A0C",
      cardBackground: "#16161A",
      primaryText: "#F5F5F7",
      secondaryText: "#9E9EA7",
      accentGold: "#E5C07B",
      border: "#26262E",
      buttonBackground: "#E5C07B",
      buttonText: "#0A0A0C",
    },
    typography: {
      headingFont: "Syne",
      bodyFont: "Inter",
    },
    geometry: {
      buttonRadius: "rounded-xl",
      cardRadius: "rounded-2xl",
      buttonStyle: "solid",
    },
    backgroundConfig: {
      type: "canvas_constellation",
      patternColor: "#E5C07B",
      patternOpacity: 0.65,
      particleSpeed: 0.9,
    },
  },
  {
    id: "emerald_champagne",
    name: "Emerald & Champagne",
    palette: {
      background: "#062419",
      cardBackground: "#0C3829",
      primaryText: "#FBF7EE",
      secondaryText: "#8FA89B",
      accentGold: "#E2C482",
      border: "#1A4D3B",
      buttonBackground: "#E2C482",
      buttonText: "#062419",
    },
    typography: {
      headingFont: "Cormorant Garamond",
      bodyFont: "Plus Jakarta Sans",
    },
    geometry: {
      buttonRadius: "rounded-xl",
      cardRadius: "rounded-2xl",
      buttonStyle: "solid",
    },
    backgroundConfig: {
      type: "canvas_aurora_waves",
      patternColor: "#E2C482",
      patternOpacity: 0.6,
      particleSpeed: 0.8,
    },
  },
  {
    id: "parisian_rose",
    name: "Parisian Rose",
    palette: {
      background: "#FAF5F0",
      cardBackground: "#FFFFFF",
      primaryText: "#2A2120",
      secondaryText: "#A68A85",
      accentGold: "#C59B7A",
      border: "#EFE3D8",
      buttonBackground: "#2A2120",
      buttonText: "#FAF5F0",
    },
    typography: {
      headingFont: "Playfair Display",
      bodyFont: "Outfit",
    },
    geometry: {
      buttonRadius: "rounded-2xl",
      cardRadius: "rounded-3xl",
      buttonStyle: "soft",
    },
    backgroundConfig: {
      type: "subtle_noise",
      patternColor: "#C59B7A",
      patternOpacity: 0.5,
      particleSpeed: 1,
    },
  },
  {
    id: "monaco_sapphire",
    name: "Monaco Sapphire",
    palette: {
      background: "#0B132B",
      cardBackground: "#131E3D",
      primaryText: "#FFFFFF",
      secondaryText: "#8B9EC7",
      accentGold: "#3B82F6",
      border: "#1E2D56",
      buttonBackground: "#3B82F6",
      buttonText: "#FFFFFF",
    },
    typography: {
      headingFont: "Plus Jakarta Sans",
      bodyFont: "Inter",
    },
    geometry: {
      buttonRadius: "rounded-xl",
      cardRadius: "rounded-2xl",
      buttonStyle: "solid",
    },
    backgroundConfig: {
      type: "gradient_mesh",
      patternColor: "#3B82F6",
      patternOpacity: 0.7,
      particleSpeed: 1.2,
    },
  },
  {
    id: "cyberpunk_cyan",
    name: "Cyberpunk Cyan",
    palette: {
      background: "#08090C",
      cardBackground: "#101218",
      primaryText: "#F0F6FC",
      secondaryText: "#7D8590",
      accentGold: "#00F0FF",
      border: "#21262D",
      buttonBackground: "#00F0FF",
      buttonText: "#08090C",
    },
    typography: {
      headingFont: "Space Grotesk",
      bodyFont: "Space Grotesk",
    },
    geometry: {
      buttonRadius: "rounded-lg",
      cardRadius: "rounded-xl",
      buttonStyle: "neon",
    },
    backgroundConfig: {
      type: "canvas_stardust",
      patternColor: "#00F0FF",
      patternOpacity: 0.8,
      particleSpeed: 1.4,
    },
  },
  {
    id: "tokyo_sakura",
    name: "Tokyo Sakura",
    palette: {
      background: "#0F0E17",
      cardBackground: "#1B1A26",
      primaryText: "#FFFFFE",
      secondaryText: "#A7A9BE",
      accentGold: "#FF8EAD",
      border: "#2E2D3E",
      buttonBackground: "#FF8EAD",
      buttonText: "#0F0E17",
    },
    typography: {
      headingFont: "Outfit",
      bodyFont: "Outfit",
    },
    geometry: {
      buttonRadius: "rounded-2xl",
      cardRadius: "rounded-3xl",
      buttonStyle: "pill",
    },
    backgroundConfig: {
      type: "gradient_radial",
      patternColor: "#FF8EAD",
      patternOpacity: 0.65,
      particleSpeed: 1,
    },
  },
  {
    id: "kyoto_matcha",
    name: "Kyoto Matcha",
    palette: {
      background: "#F4F5F0",
      cardBackground: "#FFFFFF",
      primaryText: "#202621",
      secondaryText: "#768479",
      accentGold: "#52796F",
      border: "#DDE3DB",
      buttonBackground: "#202621",
      buttonText: "#F4F5F0",
    },
    typography: {
      headingFont: "Cormorant Garamond",
      bodyFont: "Inter",
    },
    geometry: {
      buttonRadius: "rounded-xl",
      cardRadius: "rounded-2xl",
      buttonStyle: "outline",
    },
    backgroundConfig: {
      type: "dot_grid",
      patternColor: "#52796F",
      patternOpacity: 0.7,
      particleSpeed: 1,
    },
  },
  {
    id: "studio_cinema",
    name: "Studio Cinema Dark",
    palette: {
      background: "#111114",
      cardBackground: "#1A1A20",
      primaryText: "#F5F5FA",
      secondaryText: "#9494A3",
      accentGold: "#E50914",
      border: "#2B2B36",
      buttonBackground: "#E50914",
      buttonText: "#FFFFFF",
    },
    typography: {
      headingFont: "Syne",
      bodyFont: "Inter",
    },
    geometry: {
      buttonRadius: "rounded-xl",
      cardRadius: "rounded-2xl",
      buttonStyle: "solid",
    },
    backgroundConfig: {
      type: "canvas_constellation",
      patternColor: "#E50914",
      patternOpacity: 0.6,
      particleSpeed: 1.1,
    },
  },
];
