import { 
  ProfileThemeConfig, 
  CardDesignConfig, 
  ProfileBlock 
} from "@/types/builder";

export type TemplateCategory = 
  | "Haute Couture & Runway" 
  | "Quiet Luxury & Heritage" 
  | "Tech & AI Founders" 
  | "Art Direction & Editorial" 
  | "Nightlife & Cyber Chic" 
  | "Artisanal & Atelier"
  | "Wellness & High Living"
  | "Entertainment & Film";

export type TemplateBadge = 
  | "SIGNATURE" 
  | "POPULAR" 
  | "NEW" 
  | "MINIMAL" 
  | "EDITORIAL" 
  | "HIGH FASHION"
  | "LIMITED"
  | "EXCLUSIVE"
  | "AVANT-GARDE";

export interface FullPageTemplate {
  id: string;
  name: string;
  category: TemplateCategory;
  tagline: string;
  description: string;
  badge: TemplateBadge;
  heroCoverUrl: string;
  avatarUrl: string;
  theme: ProfileThemeConfig;
  cardDesign: CardDesignConfig;
  demoMeta: {
    displayName: string;
    handle: string;
    bio: string;
    location: string;
    email: string;
    phone: string;
    verified: boolean;
  };
  sampleBlocks: ProfileBlock[];
}

export const FULL_PAGE_TEMPLATES: FullPageTemplate[] = [
  // 1. ASOOBI IMPERIAL GOLD
  {
    id: "tmpl_imperial_gold",
    name: "Asoobi Imperial Gold",
    category: "Haute Couture & Runway",
    tagline: "The iconic Milan runway aesthetic with constellation particle flow",
    description: "Cream pearl surfaces, hand-gilded 24k gold hairline borders, and warm champagne highlights designed for high-fashion stylists.",
    badge: "SIGNATURE",
    heroCoverUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "asoobi_luxury_gold",
      name: "Asoobi Signature Gold",
      palette: {
        background: "#F9F9F7",
        cardBackground: "#FFFFFF",
        primaryText: "#1A1C20",
        secondaryText: "#918355",
        accentGold: "#D4AF37",
        border: "#E5E0D2",
        buttonBackground: "#D4AF37",
        buttonText: "#1A1C20",
      },
      typography: {
        headingFont: "Playfair Display",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "shadow_gold",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "canvas_stardust",
        patternColor: "#D4AF37",
        patternOpacity: 0.6,
        particleSpeed: 0.8,
      },
    },
    cardDesign: {
      presetId: "luxury_gold",
      name: "Asoobi Imperial Gold",
      borderRadius: "rounded-2xl",
      borderStyle: "gold_accent",
      shadowStyle: "gold_glow",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#D4AF37",
    },
    demoMeta: {
      displayName: "Elena Vance",
      handle: "elena_vance",
      bio: "Digital Stylist & Luxury Creative Director. Curating aesthetics, high-fashion campaigns & editorial drops in Milan & Paris.",
      location: "Milan, Italy",
      email: "elena.vance@asoobi.studio",
      phone: "+39 02 8945 2201",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-ig-1",
        type: "featured_link",
        position: 0,
        title: "Fall/Winter Capsule Campaign '26",
        subtitle: "Exclusive lookbook and behind-the-scenes film",
        isVisible: true,
        isArchived: false,
        url: "https://asoobi.com/campaign",
        badgeText: "NEW DROP",
        highlightCoverUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80",
        callToAction: "Explore Lookbook",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
      {
        id: "b-ig-2",
        type: "standard_link",
        position: 1,
        title: "Vogue Italia Feature: The New Renaissance",
        subtitle: "Read the full 12-page interview",
        isVisible: true,
        isArchived: false,
        url: "https://vogue.it",
        openInNewTab: true,
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
      {
        id: "b-ig-3",
        type: "discount_code",
        position: 2,
        title: "Asoobi Private Atelier Code",
        subtitle: "Private 20% discount on bespoke garments",
        isVisible: true,
        isArchived: false,
        code: "ATELIER20",
        discountPercentageOrValue: "20% OFF",
        brandName: "Asoobi Haute Couture",
        expiryNote: "Redeemable at the Via Montenapoleone showroom",
        destinationUrl: "https://asoobi.com/private-client",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 2. SILK NOIR MINIMALIST
  {
    id: "tmpl_silk_noir",
    name: "Silk Noir Minimalist",
    category: "Quiet Luxury & Heritage",
    tagline: "Deep obsidian tones and razor-thin silver hairline elegance",
    description: "Deep obsidian tones, razor-thin silver hairline cards, and Cinzel serif typography tailored for discreet wealth and private offices.",
    badge: "MINIMAL",
    heroCoverUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "silk_noir",
      name: "Silk Noir",
      palette: {
        background: "#0C0C0E",
        cardBackground: "#17171A",
        primaryText: "#F5F5F7",
        secondaryText: "#8E8E93",
        accentGold: "#E0D7C6",
        border: "#26262B",
        buttonBackground: "#F5F5F7",
        buttonText: "#0C0C0E",
      },
      typography: {
        headingFont: "Cinzel",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-xl",
        buttonStyle: "solid",
        buttonShadow: "none",
      },
      backgroundConfig: {
        type: "canvas_stardust",
        patternColor: "#E0D7C6",
        patternOpacity: 0.5,
        particleSpeed: 0.6,
      },
    },
    cardDesign: {
      presetId: "minimal_flat",
      name: "Minimal Silk Noir",
      borderRadius: "rounded-xl",
      borderStyle: "subtle",
      shadowStyle: "soft",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#E0D7C6",
    },
    demoMeta: {
      displayName: "Christian de Mar",
      handle: "christian_demar",
      bio: "Private Equity Principal & Heritage Asset Curator. Advisory on Swiss horology, fine art provenance, and private family offices.",
      location: "Zurich • Geneva",
      email: "c.demar@heritage-advisory.ch",
      phone: "+41 22 819 9000",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-sn-1",
        type: "standard_link",
        position: 0,
        title: "Q3 2026 Private Wealth & Horology Memo",
        subtitle: "Confidential market analysis for institutional collectors",
        isVisible: true,
        isArchived: false,
        url: "https://heritage-advisory.ch/memo",
        openInNewTab: true,
        accessRules: { isLocked: true, password: "VAULT", barrier: "protected", scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
      {
        id: "b-sn-2",
        type: "featured_link",
        position: 1,
        title: "Geneva Vault: Historical Patek & Vacheron Archives",
        subtitle: "Private viewing by appointment only",
        isVisible: true,
        isArchived: false,
        url: "https://heritage-advisory.ch/vault",
        badgeText: "CONFIDENTIAL",
        highlightCoverUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80",
        callToAction: "Request Access",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 3. MONACO SAPPHIRE HIGH-JEWELRY
  {
    id: "tmpl_monaco_sapphire",
    name: "Monaco Sapphire High-Jewelry",
    category: "Quiet Luxury & Heritage",
    tagline: "Frosted royal sapphire glass with Cormorant Garamond typography",
    description: "Deep oceanic blue gradients, luminous cyan luminescence, and ethereal glassmorphism cards suited for jewelers and yacht clubs.",
    badge: "HIGH FASHION",
    heroCoverUrl: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "monaco_sapphire",
      name: "Monaco Sapphire",
      palette: {
        background: "#081026",
        cardBackground: "#0E1C3D",
        primaryText: "#F0F6FF",
        secondaryText: "#93C5FD",
        accentGold: "#38BDF8",
        border: "#1E3A8A",
        buttonBackground: "#2563EB",
        buttonText: "#FFFFFF",
      },
      typography: {
        headingFont: "Cormorant Garamond",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-2xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "glass",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "canvas_aurora_waves",
        patternColor: "#3B82F6",
        patternOpacity: 0.65,
        particleSpeed: 0.9,
      },
    },
    cardDesign: {
      presetId: "glassmorphism",
      name: "High Fashion Glassmorphism",
      borderRadius: "rounded-2xl",
      borderStyle: "glow",
      shadowStyle: "neon",
      surfaceStyle: "glass",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#3B82F6",
    },
    demoMeta: {
      displayName: "Maison de Roche",
      handle: "maison_de_roche",
      bio: "Haute Joaillerie & High-Jewelry Atelier. Rare Burmese sapphires, Colombian emeralds, and bespoke imperial tiaras since 1912.",
      location: "Monte Carlo • Place Vendôme",
      email: "concierge@maisonderoche.mc",
      phone: "+377 98 06 20 00",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-ms-1",
        type: "featured_link",
        position: 0,
        title: "2026 High Jewelry High-Seas Gala",
        subtitle: "Monaco Yacht Club Private Ballroom Showcase",
        isVisible: true,
        isArchived: false,
        url: "https://maisonderoche.mc/gala",
        badgeText: "MONTE CARLO",
        highlightCoverUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
        callToAction: "Inquire for Table",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
      {
        id: "b-ms-2",
        type: "standard_link",
        position: 1,
        title: "Place Vendôme Atelier Appointment Booking",
        subtitle: "Private gemological consultation with Master Jeweler",
        isVisible: true,
        isArchived: false,
        url: "https://maisonderoche.mc/book",
        openInNewTab: true,
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 4. TOKYO CYBER SAKURA
  {
    id: "tmpl_tokyo_cyber",
    name: "Tokyo Cyber Sakura",
    category: "Nightlife & Cyber Chic",
    tagline: "Midnight plum & neon sakura gradient with pill cards",
    description: "Electric neon magenta and sakura accents layered over deep plum shadows with rounded pill geometry for electronic artists and nightlife icons.",
    badge: "POPULAR",
    heroCoverUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "tokyo_cyber",
      name: "Tokyo Cyber Sakura",
      palette: {
        background: "#160D24",
        cardBackground: "#24163B",
        primaryText: "#FFF0F5",
        secondaryText: "#E0A8CE",
        accentGold: "#FF8EAD",
        border: "#44276E",
        buttonBackground: "#FF3385",
        buttonText: "#FFFFFF",
      },
      typography: {
        headingFont: "Outfit",
        bodyFont: "Plus Jakarta Sans",
      },
      geometry: {
        buttonRadius: "rounded-full",
        cardRadius: "rounded-3xl",
        buttonStyle: "pill",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "gradient_radial",
        patternColor: "#FF8EAD",
        patternOpacity: 0.6,
        particleSpeed: 1.2,
      },
    },
    cardDesign: {
      presetId: "cyber_neon",
      name: "Cyber Neon Glow",
      borderRadius: "rounded-3xl",
      borderStyle: "glow",
      shadowStyle: "neon",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#FF8EAD",
    },
    demoMeta: {
      displayName: "Ren Takahashi (高橋 蓮)",
      handle: "ren_takahashi",
      bio: "Electronic Soundscape Architect & Generative Visualist. Resident DJ @ Shibuya Sound Museum • Live AV Sets in Tokyo & Berlin.",
      location: "Tokyo, Japan",
      email: "booking@rentakahashi.jp",
      phone: "+81 3 5410 8820",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-tc-1",
        type: "featured_link",
        position: 0,
        title: "Live at Womb Shibuya [4K Spatial Audio Stream]",
        subtitle: "3-hour hypnotic cyber-techno set recorded live",
        isVisible: true,
        isArchived: false,
        url: "https://youtube.com",
        badgeText: "NEW STREAM",
        highlightCoverUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80",
        callToAction: "Watch in 4K",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
      {
        id: "b-tc-2",
        type: "standard_link",
        position: 1,
        title: "Spotify: Neon Shinjuku Rain Playlist (42k followers)",
        subtitle: "Curated dark ambient & melodic synthwave",
        isVisible: true,
        isArchived: false,
        url: "https://spotify.com",
        openInNewTab: true,
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 5. SILICON VALLEY AI ARCHITECT
  {
    id: "tmpl_sv_ai_architect",
    name: "Silicon Valley AI Architect",
    category: "Tech & AI Founders",
    tagline: "Bento grid styling, Space Grotesk font and emerald particle matrix",
    description: "Monospaced technical grid, sharp emerald terminal highlights, and bento tile aesthetics built for AI researchers, YC founders and engineers.",
    badge: "POPULAR",
    heroCoverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "sv_ai",
      name: "Silicon Valley AI",
      palette: {
        background: "#0A0D12",
        cardBackground: "#121820",
        primaryText: "#F0F4F8",
        secondaryText: "#7E8B9B",
        accentGold: "#10B981",
        border: "#1F2937",
        buttonBackground: "#10B981",
        buttonText: "#0A0D12",
      },
      typography: {
        headingFont: "Space Grotesk",
        bodyFont: "JetBrains Mono",
      },
      geometry: {
        buttonRadius: "rounded-lg",
        cardRadius: "rounded-2xl",
        buttonStyle: "solid",
        buttonShadow: "none",
      },
      backgroundConfig: {
        type: "dot_grid",
        patternColor: "#10B981",
        patternOpacity: 0.6,
        particleSpeed: 1,
      },
    },
    cardDesign: {
      presetId: "bento_tile",
      name: "Bento Technical Grid",
      borderRadius: "rounded-2xl",
      borderStyle: "subtle",
      shadowStyle: "soft",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#10B981",
    },
    demoMeta: {
      displayName: "Dr. Julian Vance",
      handle: "julian_vance",
      bio: "Founding Engineer @ DeepReason AI (YC W26). Researching autonomous multi-agent reasoning, self-healing codebases & GPU clusters.",
      location: "San Francisco • Palo Alto",
      email: "julian@deepreason.ai",
      phone: "+1 (415) 890-2100",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-ai-1",
        type: "featured_link",
        position: 0,
        title: "DeepReason Autonomous Coding Agent [v2.4 Demo]",
        subtitle: "10x throughput benchmark beating Claude 3.7 & GPT-4.5 on SWE-bench",
        isVisible: true,
        isArchived: false,
        url: "https://deepreason.ai/demo",
        badgeText: "YC W26 DEMO",
        highlightCoverUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
        callToAction: "Try Agent Sandbox",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
      {
        id: "b-ai-2",
        type: "standard_link",
        position: 1,
        title: "GitHub: open-reasoning-framework (18.4k stars)",
        subtitle: "MIT licensed distributed reasoning framework for PyTorch & CUDA",
        isVisible: true,
        isArchived: false,
        url: "https://github.com/deepreason/open-reasoning",
        openInNewTab: true,
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
      {
        id: "b-ai-3",
        type: "standard_link",
        position: 2,
        title: "Technical Advisory & Seed Round Deck",
        subtitle: "Passcode protected for accredited angel investors",
        isVisible: true,
        isArchived: false,
        url: "https://deepreason.ai/deck",
        openInNewTab: true,
        accessRules: { isLocked: true, password: "SCALE", barrier: "protected", scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 6. PARISIAN ART DIRECTOR
  {
    id: "tmpl_parisian_couture",
    name: "Parisian Art Director",
    category: "Art Direction & Editorial",
    tagline: "Parchment surfaces, terracotta tones and Bodoni Moda typography",
    description: "Subtle tactile paper warmth, terracotta typographic highlights, and double editorial borders curated for gallerists and art directors.",
    badge: "EDITORIAL",
    heroCoverUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "parisian_art",
      name: "Parisian Art Director",
      palette: {
        background: "#F4F0E8",
        cardBackground: "#FFFFFF",
        primaryText: "#2C2523",
        secondaryText: "#877B75",
        accentGold: "#C86D51",
        border: "#E0D7CB",
        buttonBackground: "#2C2523",
        buttonText: "#F4F0E8",
      },
      typography: {
        headingFont: "Bodoni Moda",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-sm",
        cardRadius: "rounded-2xl",
        buttonStyle: "solid",
        buttonShadow: "none",
      },
      backgroundConfig: {
        type: "canvas_aurora_waves",
        patternColor: "#C86D51",
        patternOpacity: 0.45,
        particleSpeed: 0.7,
      },
    },
    cardDesign: {
      presetId: "retro_editorial",
      name: "Editorial Parchment",
      borderRadius: "rounded-2xl",
      borderStyle: "subtle",
      shadowStyle: "soft",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#C86D51",
    },
    demoMeta: {
      displayName: "Clémence Laurent",
      handle: "clemence_laurent",
      bio: "Creative Director & Literary Curator @ Éditions de Minuit. Contributing essayist for Le Figaro & Architectural Digest France.",
      location: "Paris, 6ème Arrondissement",
      email: "contact@clemencelaurent.fr",
      phone: "+33 1 42 68 55 10",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-pc-1",
        type: "featured_link",
        position: 0,
        title: "L'Ombre et la Lumière: Paris Fashion Monograph",
        subtitle: "A 340-page clothbound retrospective published by Rizzoli",
        isVisible: true,
        isArchived: false,
        url: "https://rizzoli.com/monograph",
        badgeText: "NEW MONOGRAPH",
        highlightCoverUrl: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=800&q=80",
        callToAction: "Order First Edition",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
      {
        id: "b-pc-2",
        type: "standard_link",
        position: 1,
        title: "Substack: Carnet d'un Flâneur Parisien",
        subtitle: "Weekly dispatch on Parisian galleries, secret bistros & poetry",
        isVisible: true,
        isArchived: false,
        url: "https://substack.com",
        openInNewTab: true,
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 7. MILANESE ATELIER AMBER
  {
    id: "tmpl_milan_amber",
    name: "Milanese Atelier Amber",
    category: "Haute Couture & Runway",
    tagline: "Warm anthracite with electric amber and Syne display typography",
    description: "Dark architectural surfaces with warm amber illumination, and geometric Syne headings designed for industrial designers and bespoke leather artisans.",
    badge: "NEW",
    heroCoverUrl: "https://images.unsplash.com/photo-1513094735237-8f2714d57c13?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "milan_amber",
      name: "Milan Amber",
      palette: {
        background: "#141416",
        cardBackground: "#202024",
        primaryText: "#F8F8F8",
        secondaryText: "#A0A0A8",
        accentGold: "#F59E0B",
        border: "#2C2C32",
        buttonBackground: "#F59E0B",
        buttonText: "#141416",
      },
      typography: {
        headingFont: "Syne",
        bodyFont: "Plus Jakarta Sans",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "shadow_gold",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "canvas_stardust",
        patternColor: "#F59E0B",
        patternOpacity: 0.7,
        particleSpeed: 1,
      },
    },
    cardDesign: {
      presetId: "horology_gilded",
      name: "Atelier Amber Glow",
      borderRadius: "rounded-2xl",
      borderStyle: "gold_accent",
      shadowStyle: "gold_glow",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#F59E0B",
    },
    demoMeta: {
      displayName: "Mateo Rossi",
      handle: "mateo_rossi_atelier",
      bio: "Master Leather Artisan & Architectural Furniture Craftsman. Handmade bridle leather trunks, salon chairs & sculptural desk objects.",
      location: "Milan, Brera Design District",
      email: "atelier@mateorossi.it",
      phone: "+39 02 7780 4410",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-ma-1",
        type: "featured_link",
        position: 0,
        title: "Salone del Mobile '26 Milan Solo Exhibition",
        subtitle: "12 bespoke hand-stitched leather lounge chairs on display",
        isVisible: true,
        isArchived: false,
        url: "https://salonedelmobile.it",
        badgeText: "EXHIBITION",
        highlightCoverUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80",
        callToAction: "Book Viewing Pass",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
      {
        id: "b-ma-2",
        type: "standard_link",
        position: 1,
        title: "Bespoke Trunk Commission Waiting List",
        subtitle: "Currently accepting 6 custom commissions for Q4",
        isVisible: true,
        isArchived: false,
        url: "https://mateorossi.it/commissions",
        openInNewTab: true,
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 8. ST. TROPEZ SUNSET RIVIERA
  {
    id: "tmpl_sunset_riviera",
    name: "St. Tropez Sunset Riviera",
    category: "Quiet Luxury & Heritage",
    tagline: "Warm terracotta and French Riviera azure with rounded-3xl floating cards",
    description: "Sun-drenched Mediterranean colors, soft peach hues, and flowing rounded-3xl elevation cards designed for resort wear designers and travel tastemakers.",
    badge: "NEW",
    heroCoverUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "sunset_riviera",
      name: "Sunset Riviera",
      palette: {
        background: "#FFFBF7",
        cardBackground: "#FFFFFF",
        primaryText: "#2C1810",
        secondaryText: "#9C6B58",
        accentGold: "#E07A5F",
        border: "#F3E8E2",
        buttonBackground: "#E07A5F",
        buttonText: "#FFFFFF",
      },
      typography: {
        headingFont: "Playfair Display",
        bodyFont: "Plus Jakarta Sans",
      },
      geometry: {
        buttonRadius: "rounded-2xl",
        cardRadius: "rounded-3xl",
        buttonStyle: "solid",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "canvas_stardust",
        patternColor: "#E07A5F",
        patternOpacity: 0.5,
        particleSpeed: 0.8,
      },
    },
    cardDesign: {
      presetId: "floating_elevation",
      name: "Sunset Riviera Rose",
      borderRadius: "rounded-3xl",
      borderStyle: "none",
      shadowStyle: "floating",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "spacious",
      accentColor: "#E07A5F",
    },
    demoMeta: {
      displayName: "Elena Vance",
      handle: "elena_vance",
      bio: "Resort Wear Designer & Côte d'Azur Travel Stylist. Living between Cap d'Antibes and St. Tropez.",
      location: "St. Tropez • Cannes",
      email: "elena.vance@asoobi.studio",
      phone: "+39 02 8945 2201",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-sr-1",
        type: "featured_link",
        position: 0,
        title: "Summer '26 Silk Kaftan Collection",
        subtitle: "Hand-printed Italian silk resort wear directly from our atelier",
        isVisible: true,
        isArchived: false,
        url: "https://asoobi.studio/riviera",
        badgeText: "SUMMER DROP",
        highlightCoverUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        callToAction: "Shop Collection",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 9. NORDIC BIRCH & SAGE ATELIER
  {
    id: "tmpl_nordic_sage",
    name: "Nordic Birch & Sage Atelier",
    category: "Artisanal & Atelier",
    tagline: "Subtle sage green, limestone paper, and wabi-sabi tactile calm",
    description: "Earthy Scandinavian minimalism pairing calm sage green, limestone textures, and organic wabi-sabi curves for ceramicists and slow-living makers.",
    badge: "MINIMAL",
    heroCoverUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "nordic_sage",
      name: "Nordic Sage",
      palette: {
        background: "#F4F6F4",
        cardBackground: "#FFFFFF",
        primaryText: "#202A24",
        secondaryText: "#6B7C71",
        accentGold: "#4A6B53",
        border: "#DEE5DF",
        buttonBackground: "#4A6B53",
        buttonText: "#FFFFFF",
      },
      typography: {
        headingFont: "Plus Jakarta Sans",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "solid",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "dot_grid",
        patternColor: "#4A6B53",
        patternOpacity: 0.5,
        particleSpeed: 0.8,
      },
    },
    cardDesign: {
      presetId: "wabi_sabi",
      name: "Nordic Organic Stone",
      borderRadius: "rounded-2xl",
      borderStyle: "subtle",
      shadowStyle: "soft",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#4A6B53",
    },
    demoMeta: {
      displayName: "Astrid Lindqvist",
      handle: "astrid_lindqvist",
      bio: "Architectural Ceramicist & Slow Living Maker. Studio in Stockholm Archipelago • Functional stoneware & raw clay vessels.",
      location: "Stockholm, Sweden",
      email: "hej@astridlindqvist.se",
      phone: "+46 8 555 12 34",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-ns-1",
        type: "featured_link",
        position: 0,
        title: "Archipelago Stoneware Drop No. 08",
        subtitle: "Only 45 hand-thrown vases and matcha bowls available",
        isVisible: true,
        isArchived: false,
        url: "https://astridlindqvist.se/drop08",
        badgeText: "LIMITED BATCH",
        highlightCoverUrl: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80",
        callToAction: "View Ceramic Drop",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 10. VENETIAN VELVET CRIMSON
  {
    id: "tmpl_venetian_crimson",
    name: "Venetian Velvet Crimson",
    category: "Haute Couture & Runway",
    tagline: "Deep baroque crimson & gilded borders for opera and couture",
    description: "Lush baroque crimson velvet with 24k gilded ornaments, dramatic Bodoni Moda typography, and theatrical Italian high-fashion heritage.",
    badge: "HIGH FASHION",
    heroCoverUrl: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "venetian_crimson",
      name: "Venetian Crimson",
      palette: {
        background: "#18090C",
        cardBackground: "#281014",
        primaryText: "#FAF0F2",
        secondaryText: "#C48E98",
        accentGold: "#E5A93C",
        border: "#4A1D24",
        buttonBackground: "#A11D33",
        buttonText: "#FAF0F2",
      },
      typography: {
        headingFont: "Bodoni Moda",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "shadow_gold",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "canvas_stardust",
        patternColor: "#E5A93C",
        patternOpacity: 0.65,
        particleSpeed: 0.9,
      },
    },
    cardDesign: {
      presetId: "luxury_gold",
      name: "Baroque Gilded Velvet",
      borderRadius: "rounded-2xl",
      borderStyle: "gold_accent",
      shadowStyle: "gold_glow",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#E5A93C",
    },
    demoMeta: {
      displayName: "Isabella Contarini",
      handle: "isabella_contarini",
      bio: "Prima Donna Soprano & Baroque Costume Historian. Performing @ Teatro La Fenice Venice & Royal Opera House London.",
      location: "Venice, San Marco",
      email: "management@isabellacontarini.it",
      phone: "+39 041 786 5500",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-vc-1",
        type: "featured_link",
        position: 0,
        title: "Vivaldi's Orlando Furioso: Live at La Fenice",
        subtitle: "Autumn season opening performance ticket reservations",
        isVisible: true,
        isArchived: false,
        url: "https://teatrolafenice.it",
        badgeText: "PREMIERE",
        highlightCoverUrl: "https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=800&q=80",
        callToAction: "Reserve Gala Seats",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 11. KYOTO WABI-SABI ZEN
  {
    id: "tmpl_kyoto_zen",
    name: "Kyoto Wabi-Sabi Zen",
    category: "Artisanal & Atelier",
    tagline: "Natural slate, unbleached washi paper and ceremonial matcha olive",
    description: "Quiet Zen aesthetic grounded in Japanese paper craftsmanship, dark basalt stone, and muted ceremonial matcha for tea masters and ceramicists.",
    badge: "AVANT-GARDE",
    heroCoverUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "kyoto_zen",
      name: "Kyoto Wabi-Sabi",
      palette: {
        background: "#1C1E1F",
        cardBackground: "#26292B",
        primaryText: "#F2EFE9",
        secondaryText: "#9CA39E",
        accentGold: "#8F9E74",
        border: "#363A3D",
        buttonBackground: "#606C38",
        buttonText: "#F2EFE9",
      },
      typography: {
        headingFont: "Cormorant Garamond",
        bodyFont: "Plus Jakarta Sans",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "solid",
        buttonShadow: "none",
      },
      backgroundConfig: {
        type: "subtle_noise",
        patternColor: "#8F9E74",
        patternOpacity: 0.4,
        particleSpeed: 0.5,
      },
    },
    cardDesign: {
      presetId: "wabi_sabi",
      name: "Kyoto Basalt & Bamboo",
      borderRadius: "rounded-2xl",
      borderStyle: "subtle",
      shadowStyle: "soft",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#8F9E74",
    },
    demoMeta: {
      displayName: "Kenjiro Ito (伊藤 健二郎)",
      handle: "kenjiro_chado",
      bio: "15th Generation Urasenke Chado Master & Bizen Ware Potter. Curating traditional tea ceremonies and seasonal bamboo utensils.",
      location: "Kyoto, Higashiyama",
      email: "info@kenjiro-ito.kyoto.jp",
      phone: "+81 75 561 8820",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-kz-1",
        type: "featured_link",
        position: 0,
        title: "Autumn Chado Ceremony & Tea Gathering",
        subtitle: "Exclusive 6-guest private tea gathering overlooking Ginkaku-ji gardens",
        isVisible: true,
        isArchived: false,
        url: "https://kenjiro-ito.kyoto.jp/ceremony",
        badgeText: "PRIVATE SITTING",
        highlightCoverUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
        callToAction: "Request Invitation",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
      {
        id: "b-kz-2",
        type: "standard_link",
        position: 1,
        title: "Hand-carved Bamboo Chashaku & Bizen Chawan",
        subtitle: "Wood-fired unglazed stoneware vessels made in Okayama",
        isVisible: true,
        isArchived: false,
        url: "https://kenjiro-ito.kyoto.jp/pottery",
        openInNewTab: true,
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 12. BEVERLY HILLS AESTHETIC MEDSPA
  {
    id: "tmpl_beverly_hills_aesthetic",
    name: "Beverly Hills Aesthetic MedSpa",
    category: "Wellness & High Living",
    tagline: "Soft rose quartz, champagne accents and soft claymorphism cards",
    description: "Pristine clinical luxury combining soft blush stone, warm champagne metallics, and gentle rounded claymorphism cards for dermatologists and cosmetic doctors.",
    badge: "EXCLUSIVE",
    heroCoverUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "beverly_hills_aesthetic",
      name: "Beverly Hills Rose",
      palette: {
        background: "#FFF8F9",
        cardBackground: "#FFFFFF",
        primaryText: "#3A2A2F",
        secondaryText: "#8E727A",
        accentGold: "#DDA7A5",
        border: "#F5E2E4",
        buttonBackground: "#DDA7A5",
        buttonText: "#3A2A2F",
      },
      typography: {
        headingFont: "Playfair Display",
        bodyFont: "Outfit",
      },
      geometry: {
        buttonRadius: "rounded-2xl",
        cardRadius: "rounded-3xl",
        buttonStyle: "solid",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "floating_bubbles",
        patternColor: "#DDA7A5",
        patternOpacity: 0.5,
        particleSpeed: 0.7,
      },
    },
    cardDesign: {
      presetId: "claymorphism",
      name: "Rose Quartz Clay",
      borderRadius: "rounded-3xl",
      borderStyle: "subtle",
      shadowStyle: "clay_3d",
      surfaceStyle: "clay",
      hoverEffect: "lift",
      padding: "spacious",
      accentColor: "#DDA7A5",
    },
    demoMeta: {
      displayName: "Dr. Vivienne Vance, MD",
      handle: "dr_vivienne_vance",
      bio: "Board-Certified Aesthetic Dermatologist & Longevity Clinician. Founder of The Vance Skin Institute on Rodeo Drive.",
      location: "Beverly Hills, CA",
      email: "concierge@vanceinstitute.com",
      phone: "+1 (310) 902-8400",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-bh-1",
        type: "featured_link",
        position: 0,
        title: "Cellular Longevity Facial & Exosome Therapy",
        subtitle: "The signature treatment featured in Vogue & Harper's Bazaar",
        isVisible: true,
        isArchived: false,
        url: "https://vanceinstitute.com/treatments",
        badgeText: "SIGNATURE PROTOCOL",
        highlightCoverUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80",
        callToAction: "Book Rodeo Drive Clinic",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 13. BERLIN BERGHAIN INDUSTRIAL
  {
    id: "tmpl_berlin_underground",
    name: "Berlin Berghain Industrial",
    category: "Nightlife & Cyber Chic",
    tagline: "Raw concrete dark, brutalist steel and electric hazard yellow",
    description: "Uncompromising underground techno brutalism with raw dark carbon, sharp stark borders, and high-impact industrial yellow typography.",
    badge: "AVANT-GARDE",
    heroCoverUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "berlin_industrial",
      name: "Berlin Industrial",
      palette: {
        background: "#0E0F10",
        cardBackground: "#18191C",
        primaryText: "#F0F0F2",
        secondaryText: "#88898C",
        accentGold: "#FACC15",
        border: "#28292D",
        buttonBackground: "#FACC15",
        buttonText: "#0E0F10",
      },
      typography: {
        headingFont: "Space Grotesk",
        bodyFont: "JetBrains Mono",
      },
      geometry: {
        buttonRadius: "rounded-none",
        cardRadius: "rounded-lg",
        buttonStyle: "brutalist",
        buttonShadow: "hard_offset",
      },
      backgroundConfig: {
        type: "cyber_matrix",
        patternColor: "#FACC15",
        patternOpacity: 0.55,
        particleSpeed: 1.3,
      },
    },
    cardDesign: {
      presetId: "neo_brutalist",
      name: "Brutalist Steel & Hazard",
      borderRadius: "rounded-none",
      borderStyle: "brutalist_bold",
      shadowStyle: "hard_brutalist",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#FACC15",
    },
    demoMeta: {
      displayName: "Klaus Richter",
      handle: "klaus_richter_audio",
      bio: "Modular Synthesist & Techno Producer. Resident Live Performer in Berlin, Tbilisi & Amsterdam • Hardware-only analog recordings.",
      location: "Berlin, Kreuzberg",
      email: "booking@klausrichter.de",
      phone: "+49 30 695 8810",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-bi-1",
        type: "featured_link",
        position: 0,
        title: "KRAFTWERK Berlin Live Analog Archive [2-Hour FLAC]",
        subtitle: "Direct uncompressed stereo soundboard capture",
        isVisible: true,
        isArchived: false,
        url: "https://klausrichter.de/archive",
        badgeText: "FLAC DOWNLOAD",
        highlightCoverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80",
        callToAction: "Download High-Res Audio",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 14. SAVILE ROW MASTER TAILOR
  {
    id: "tmpl_savile_row_bespoke",
    name: "Savile Row Master Tailor",
    category: "Quiet Luxury & Heritage",
    tagline: "Midnight navy worsted wool, stitched saddle borders and brass gold",
    description: "Distinguished British tailoring heritage featuring rich midnight navy, saddle-stitched borders, and classic Cinzel typography for heritage purveyors.",
    badge: "SIGNATURE",
    heroCoverUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "savile_row",
      name: "Savile Row Navy",
      palette: {
        background: "#080F1E",
        cardBackground: "#111C33",
        primaryText: "#F8FAFC",
        secondaryText: "#94A3B8",
        accentGold: "#D4AF37",
        border: "#1E2F52",
        buttonBackground: "#D4AF37",
        buttonText: "#080F1E",
      },
      typography: {
        headingFont: "Cinzel",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-lg",
        cardRadius: "rounded-xl",
        buttonStyle: "shadow_gold",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "art_deco_lattice",
        patternColor: "#D4AF37",
        patternOpacity: 0.5,
        particleSpeed: 0.6,
      },
    },
    cardDesign: {
      presetId: "leather_stitch",
      name: "Savile Saddle Stitch",
      borderRadius: "rounded-xl",
      borderStyle: "leather_stitch",
      shadowStyle: "soft",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#D4AF37",
    },
    demoMeta: {
      displayName: "Arthur Pendelton & Sons",
      handle: "pendelton_savilerow",
      bio: "Royal Warrant Bespoke Tailors Since 1884. Bespoke three-piece suits cut from Dormeuil & Scabal cloths on Savile Row.",
      location: "Savile Row, Mayfair, London",
      email: "fittings@pendelton-tailors.co.uk",
      phone: "+44 20 7493 8811",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-sr-1",
        type: "featured_link",
        position: 0,
        title: "Book Bespoke Fitting: London & New York Trunk Show",
        subtitle: "By-appointment fittings with Master Cutter Lord Pendelton",
        isVisible: true,
        isArchived: false,
        url: "https://pendelton-tailors.co.uk/book",
        badgeText: "ROYAL WARRANT",
        highlightCoverUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
        callToAction: "Schedule Private Fitting",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 15. LAKE COMO VILLA FLORA
  {
    id: "tmpl_lake_como_villa",
    name: "Lake Como Villa & Dolce Vita",
    category: "Quiet Luxury & Heritage",
    tagline: "Terracotta sun, Como deep cobalt and warm Italian villa ivory",
    description: "Sunny Mediterranean aristocracy pairing deep Como waters, terracotta clay, and airy floating cards for Italian villa owners and private concierges.",
    badge: "POPULAR",
    heroCoverUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "lake_como",
      name: "Lake Como Villa",
      palette: {
        background: "#FDFBF7",
        cardBackground: "#FFFFFF",
        primaryText: "#182C3D",
        secondaryText: "#64748B",
        accentGold: "#C36B4F",
        border: "#E7E2D6",
        buttonBackground: "#1F3F59",
        buttonText: "#FDFBF7",
      },
      typography: {
        headingFont: "Playfair Display",
        bodyFont: "Plus Jakarta Sans",
      },
      geometry: {
        buttonRadius: "rounded-2xl",
        cardRadius: "rounded-3xl",
        buttonStyle: "solid",
        buttonShadow: "subtle",
      },
      backgroundConfig: {
        type: "canvas_aurora_waves",
        patternColor: "#1F3F59",
        patternOpacity: 0.45,
        particleSpeed: 0.7,
      },
    },
    cardDesign: {
      presetId: "floating_elevation",
      name: "Dolce Vita Villa",
      borderRadius: "rounded-3xl",
      borderStyle: "none",
      shadowStyle: "floating",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "spacious",
      accentColor: "#C36B4F",
    },
    demoMeta: {
      displayName: "Contessa Alessandra Bellini",
      handle: "alessandra_bellini_como",
      bio: "Heritage Villa Curator & Riva Boat Charter Host. Overseeing private Bellagio historical estates and Michelin private dining.",
      location: "Bellagio • Lake Como, Italy",
      email: "concierge@villabellinicomo.it",
      phone: "+39 031 950 440",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-lc-1",
        type: "featured_link",
        position: 0,
        title: "Villa Bellini 18th-Century Estate & Botanical Park",
        subtitle: "Exclusive private venue booking for celebrations & weddings",
        isVisible: true,
        isArchived: false,
        url: "https://villabellinicomo.it",
        badgeText: "PRIVATE ESTATE",
        highlightCoverUrl: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80",
        callToAction: "Inquire for Estate",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 16. QUANTUM COMPUTING & DEEP TECH
  {
    id: "tmpl_quantum_deeptech",
    name: "Quantum Computing & Deep Tech",
    category: "Tech & AI Founders",
    tagline: "Deep space obsidian, quantum laser blue and technical isometric grid",
    description: "Futuristic scientific computing theme with deep space blacks, laser blue luminescence, and monospaced typography designed for physicists and deep tech founders.",
    badge: "AVANT-GARDE",
    heroCoverUrl: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "quantum_deeptech",
      name: "Quantum Obsidian",
      palette: {
        background: "#05070C",
        cardBackground: "#0B101D",
        primaryText: "#EBF3FF",
        secondaryText: "#6B82A6",
        accentGold: "#38BDF8",
        border: "#18243D",
        buttonBackground: "#0284C7",
        buttonText: "#FFFFFF",
      },
      typography: {
        headingFont: "JetBrains Mono",
        bodyFont: "Space Grotesk",
      },
      geometry: {
        buttonRadius: "rounded-lg",
        cardRadius: "rounded-xl",
        buttonStyle: "neon",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "isometric_grid",
        patternColor: "#38BDF8",
        patternOpacity: 0.6,
        particleSpeed: 1.1,
      },
    },
    cardDesign: {
      presetId: "technical_mono",
      name: "Quantum Laser Terminal",
      borderRadius: "rounded-xl",
      borderStyle: "glow",
      shadowStyle: "neon",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#38BDF8",
    },
    demoMeta: {
      displayName: "Dr. Aris Thorne",
      handle: "aris_thorne_quantum",
      bio: "Chief Quantum Scientist @ Qubit Dynamics. Researching superconducting topological qubits & cryogenic control architectures.",
      location: "Cambridge, MA • Zurich",
      email: "a.thorne@qubitdynamics.io",
      phone: "+1 (617) 495-2200",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-qd-1",
        type: "featured_link",
        position: 0,
        title: "Nature Physics Paper: 1,024 Logical Fault-Tolerant Qubits",
        subtitle: "Peer-reviewed breakthrough in quantum error correction",
        isVisible: true,
        isArchived: false,
        url: "https://nature.com/articles/quantum-breakthrough",
        badgeText: "NATURE PAPER",
        highlightCoverUrl: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=800&q=80",
        callToAction: "Read Preprint PDF",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 17. BAUHAUS DESSAU 1923
  {
    id: "tmpl_bauhaus_modernist",
    name: "Bauhaus Dessau 1923",
    category: "Art Direction & Editorial",
    tagline: "Primary Bauhaus off-white, Mondrian cobalt, and constructivist geometry",
    description: "Honoring Walter Gropius and the Bauhaus movement with functional primary colors, Swiss geometric grids, and crisp sans-serif typography.",
    badge: "EDITORIAL",
    heroCoverUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "bauhaus_1923",
      name: "Bauhaus Modernist",
      palette: {
        background: "#F5F3ED",
        cardBackground: "#FFFFFF",
        primaryText: "#18181B",
        secondaryText: "#52525B",
        accentGold: "#DC2626",
        border: "#18181B",
        buttonBackground: "#1E40AF",
        buttonText: "#FFFFFF",
      },
      typography: {
        headingFont: "Space Grotesk",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-none",
        cardRadius: "rounded-none",
        buttonStyle: "brutalist",
        buttonShadow: "hard_offset",
      },
      backgroundConfig: {
        type: "dot_grid",
        patternColor: "#DC2626",
        patternOpacity: 0.5,
        particleSpeed: 0.9,
      },
    },
    cardDesign: {
      presetId: "swiss_grid",
      name: "Bauhaus Constructivist",
      borderRadius: "rounded-none",
      borderStyle: "brutalist_bold",
      shadowStyle: "hard_brutalist",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#DC2626",
    },
    demoMeta: {
      displayName: "Greta Meyer",
      handle: "greta_meyer_bauhaus",
      bio: "Constructivist Typographer & Archival Exhibition Curator @ Bauhaus Archive Berlin. Exploring form following function.",
      location: "Berlin • Dessau",
      email: "greta@bauhaus-modern.de",
      phone: "+49 30 254 0020",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-bm-1",
        type: "featured_link",
        position: 0,
        title: "Form & Function: The 1923 Weimar Manifesto Reprints",
        subtitle: "Letterpress printed on heavy 320gsm Hahnemühle cotton stock",
        isVisible: true,
        isArchived: false,
        url: "https://bauhaus-modern.de/manifesto",
        badgeText: "LIMITED EDITION",
        highlightCoverUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80",
        callToAction: "Order Letterpress Print",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 18. IBIZA SUNSET BOHEMIAN SOL
  {
    id: "tmpl_ibiza_sol_boho",
    name: "Ibiza Sunset Bohemian Sol",
    category: "Nightlife & Cyber Chic",
    tagline: "Sun-drenched sandstone, sunset amber and bohemian teal stardust",
    description: "Balearic bohemian sunset energy featuring warm sandstone cards, terracotta ember highlights, and breezy glassmorphism designed for beach club DJs.",
    badge: "POPULAR",
    heroCoverUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "ibiza_sol",
      name: "Ibiza Bohemian Sol",
      palette: {
        background: "#1A1516",
        cardBackground: "#2B2123",
        primaryText: "#FAF6F3",
        secondaryText: "#D4A59A",
        accentGold: "#F4A261",
        border: "#423236",
        buttonBackground: "#E76F51",
        buttonText: "#FAF6F3",
      },
      typography: {
        headingFont: "Outfit",
        bodyFont: "Plus Jakarta Sans",
      },
      geometry: {
        buttonRadius: "rounded-2xl",
        cardRadius: "rounded-3xl",
        buttonStyle: "gradient_luxe",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "canvas_stardust",
        patternColor: "#F4A261",
        patternOpacity: 0.65,
        particleSpeed: 0.9,
      },
    },
    cardDesign: {
      presetId: "glassmorphism",
      name: "Balearic Sunset Glass",
      borderRadius: "rounded-3xl",
      borderStyle: "glow",
      shadowStyle: "soft",
      surfaceStyle: "glass",
      hoverEffect: "lift",
      padding: "spacious",
      accentColor: "#F4A261",
    },
    demoMeta: {
      displayName: "Sol & Luna Sessions",
      handle: "sol_luna_ibiza",
      bio: "Balearic Sunset Resident DJ @ Cala Comte & Experimental Ambient Sound Designer. Curating spiritual organic house sessions.",
      location: "Ibiza • Formentera",
      email: "bookings@sollunasessions.com",
      phone: "+34 971 34 5510",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-ib-1",
        type: "featured_link",
        position: 0,
        title: "Cala Escondida Sunset Live Session [4K Video]",
        subtitle: "Recorded live during golden hour solstice in Ibiza",
        isVisible: true,
        isArchived: false,
        url: "https://youtube.com",
        badgeText: "NEW SESSION",
        highlightCoverUrl: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=800&q=80",
        callToAction: "Watch Sunset Live",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 19. TUSCAN RESERVA ESTATE
  {
    id: "tmpl_tuscany_reserva",
    name: "Tuscan Reserva Estate",
    category: "Artisanal & Atelier",
    tagline: "Brunello wine burgundy, aged oak and Cormorant Garamond typography",
    description: "Deep noble Sangiovese tones, antique oak barrel accents, and timeless editorial styling designed for historic Italian wineries and heritage olive oil estates.",
    badge: "EXCLUSIVE",
    heroCoverUrl: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "tuscan_reserva",
      name: "Tuscan Reserva",
      palette: {
        background: "#160A0D",
        cardBackground: "#241217",
        primaryText: "#FAF4F5",
        secondaryText: "#B38C95",
        accentGold: "#DF9B52",
        border: "#3D2028",
        buttonBackground: "#6B1D2F",
        buttonText: "#FAF4F5",
      },
      typography: {
        headingFont: "Cormorant Garamond",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "shadow_gold",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "subtle_noise",
        patternColor: "#DF9B52",
        patternOpacity: 0.5,
        particleSpeed: 0.6,
      },
    },
    cardDesign: {
      presetId: "retro_editorial",
      name: "Chianti Classico Parchment",
      borderRadius: "rounded-2xl",
      borderStyle: "gold_accent",
      shadowStyle: "gold_glow",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#DF9B52",
    },
    demoMeta: {
      displayName: "Tenuta Vitivinicola Medici",
      handle: "tenutamedici_chianti",
      bio: "Historic 17th-Century Chianti Classico Gran Selezione Estate. Organic bio-dynamic single-vineyard wines aged in Slavonian oak.",
      location: "Greve in Chianti • Tuscany, Italy",
      email: "reserva@tenutamedici.it",
      phone: "+39 055 854 2200",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-tr-1",
        type: "featured_link",
        position: 0,
        title: "2018 Gran Selezione Brunello Private Allocation",
        subtitle: "Numbered wooden cases allocation for private cellar members",
        isVisible: true,
        isArchived: false,
        url: "https://tenutamedici.it/allocations",
        badgeText: "ALLOCATION ONLY",
        highlightCoverUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80",
        callToAction: "Request Cellar Allocation",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 20. 35MM HOLLYWOOD CINEMATOGRAPHER
  {
    id: "tmpl_hollywood_cinema",
    name: "35mm Hollywood Cinematographer",
    category: "Entertainment & Film",
    tagline: "Kodak darkroom black, tungsten amber and Syne film slate titles",
    description: "Cinematic film stock styling with rich deep darkroom shadows, warm tungsten spotlight amber, and bento composition for directors of photography.",
    badge: "POPULAR",
    heroCoverUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "hollywood_cinema",
      name: "35mm Film Noir",
      palette: {
        background: "#0A0A0C",
        cardBackground: "#141418",
        primaryText: "#F8F8FA",
        secondaryText: "#8E8E98",
        accentGold: "#FF9F1C",
        border: "#24242C",
        buttonBackground: "#FF9F1C",
        buttonText: "#0A0A0C",
      },
      typography: {
        headingFont: "Syne",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "solid",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "subtle_noise",
        patternColor: "#FF9F1C",
        patternOpacity: 0.5,
        particleSpeed: 0.8,
      },
    },
    cardDesign: {
      presetId: "bento_tile",
      name: "Cinematographer Film Slate",
      borderRadius: "rounded-2xl",
      borderStyle: "subtle",
      shadowStyle: "soft",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#FF9F1C",
    },
    demoMeta: {
      displayName: "Marcus Sterling, ASC",
      handle: "marcus_sterling_dp",
      bio: "Director of Photography (ASC). Shooting 35mm & 65mm IMAX for Warner Bros, A24, and Netflix • 2x Academy Award Nominee.",
      location: "Los Angeles • London",
      email: "agent@marcussterling-dp.com",
      phone: "+1 (323) 555-0199",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-hc-1",
        type: "featured_link",
        position: 0,
        title: "2026 Showreel: ARRI 65 & Panavision Anamorphic",
        subtitle: "Cinematography breakdown of recent feature film projects",
        isVisible: true,
        isArchived: false,
        url: "https://vimeo.com",
        badgeText: "2026 REEL",
        highlightCoverUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80",
        callToAction: "Watch Showreel (4K)",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 21. 3-STAR MICHELIN GASTRONOMY
  {
    id: "tmpl_michelin_gastronomy",
    name: "3-Star Michelin Haute Gastronomy",
    category: "Artisanal & Atelier",
    tagline: "Truffle black, platinum leaf and gilded gold butter luxury",
    description: "Culinary royalty with charcoal slate, pristine platinum borders, and gilded gold highlights designed for multi-star Michelin chefs and sommeliers.",
    badge: "SIGNATURE",
    heroCoverUrl: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "michelin_gastronomy",
      name: "Michelin Gastronomy",
      palette: {
        background: "#0D0D0E",
        cardBackground: "#17171A",
        primaryText: "#F4F4F6",
        secondaryText: "#A0A0A8",
        accentGold: "#EAB308",
        border: "#28282E",
        buttonBackground: "#EAB308",
        buttonText: "#0D0D0E",
      },
      typography: {
        headingFont: "Playfair Display",
        bodyFont: "Plus Jakarta Sans",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "shadow_gold",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "subtle_noise",
        patternColor: "#EAB308",
        patternOpacity: 0.5,
        particleSpeed: 0.7,
      },
    },
    cardDesign: {
      presetId: "luxury_gold",
      name: "Michelin Gold Plate",
      borderRadius: "rounded-2xl",
      borderStyle: "gold_accent",
      shadowStyle: "gold_glow",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#EAB308",
    },
    demoMeta: {
      displayName: "Chef Antoine Vasseur",
      handle: "antoine_vasseur_chef",
      bio: "Chef Patron @ L'Étoile d'Or (★★★ Michelin). Contemporary French Haute Cuisine rooted in wild Breton foraging & biodynamic terroir.",
      location: "Paris, 8ème Arrondissement",
      email: "reservations@etoiledor-paris.fr",
      phone: "+33 1 42 68 99 00",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-mg-1",
        type: "featured_link",
        position: 0,
        title: "Autumn 14-Course Degustation Menu Reservations",
        subtitle: "Seasonal menu featuring Périgord black truffle and Breton blue lobster",
        isVisible: true,
        isArchived: false,
        url: "https://etoiledor-paris.fr/reservations",
        badgeText: "★★★ MICHELIN",
        highlightCoverUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
        callToAction: "Book Table",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 22. Y2K TOKYO METALLIC POP
  {
    id: "tmpl_y2k_cyber_pop",
    name: "Y2K Tokyo Metallic Pop",
    category: "Nightlife & Cyber Chic",
    tagline: "Liquid mercury chrome, holographic magenta and cyber cyan pops",
    description: "Futuristic 2000s cyber aesthetics featuring iridescent metallic foils, liquid chrome reflections, and hyperpop energy for 3D animators and VTubers.",
    badge: "AVANT-GARDE",
    heroCoverUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "y2k_metallic",
      name: "Y2K Cyber Chrome",
      palette: {
        background: "#0E0817",
        cardBackground: "#1C122C",
        primaryText: "#FCE7F3",
        secondaryText: "#C084FC",
        accentGold: "#EC4899",
        border: "#3B1E5A",
        buttonBackground: "#EC4899",
        buttonText: "#FFFFFF",
      },
      typography: {
        headingFont: "Outfit",
        bodyFont: "Plus Jakarta Sans",
      },
      geometry: {
        buttonRadius: "rounded-full",
        cardRadius: "rounded-3xl",
        buttonStyle: "pill",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "iridescent_hologram",
        patternColor: "#EC4899",
        patternOpacity: 0.65,
        particleSpeed: 1.2,
      },
    },
    cardDesign: {
      presetId: "y2k_chrome",
      name: "Y2K Liquid Chrome",
      borderRadius: "rounded-3xl",
      borderStyle: "chrome_metallic",
      shadowStyle: "neon",
      surfaceStyle: "glass",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#EC4899",
    },
    demoMeta: {
      displayName: "Aoi Cyberpunk (青井)",
      handle: "aoi_hyperpop",
      bio: "3D Motion Artist & Hyperpop Vocalist @ Shibuya Meta-Verse. Real-time Unreal Engine 5 motion capture live performer.",
      location: "Tokyo, Harajuku",
      email: "contact@aoi-meta.jp",
      phone: "+81 3 3499 8210",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-y2k-1",
        type: "featured_link",
        position: 0,
        title: "NEO-SHIBUYA 2026 [Hyperpop Album & Virtual Vinyl]",
        subtitle: "Featuring 10 collaborative tracks with London & Seoul producers",
        isVisible: true,
        isArchived: false,
        url: "https://bandcamp.com",
        badgeText: "ALBUM DROP",
        highlightCoverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
        callToAction: "Stream on Bandcamp",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 23. GENEVA HAUTE HORLOGERIE
  {
    id: "tmpl_swiss_horology",
    name: "Geneva Haute Horlogerie",
    category: "Quiet Luxury & Heritage",
    tagline: "Hand-turned guilloché dial silver, blued steel and rose gold accents",
    description: "Swiss horological mastery featuring engine-turned guilloché surfaces, heat-blued steel accents, and Cinzel typography tailored for independent watchmakers.",
    badge: "SIGNATURE",
    heroCoverUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "geneva_horology",
      name: "Geneva Horlogerie",
      palette: {
        background: "#080C14",
        cardBackground: "#111827",
        primaryText: "#F1F5F9",
        secondaryText: "#94A3B8",
        accentGold: "#C07D53",
        border: "#1E293B",
        buttonBackground: "#C07D53",
        buttonText: "#080C14",
      },
      typography: {
        headingFont: "Cinzel",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "shadow_gold",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "art_deco_lattice",
        patternColor: "#C07D53",
        patternOpacity: 0.55,
        particleSpeed: 0.6,
      },
    },
    cardDesign: {
      presetId: "horology_gilded",
      name: "Geneva Guilloché Dial",
      borderRadius: "rounded-2xl",
      borderStyle: "gold_accent",
      shadowStyle: "gold_glow",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#C07D53",
    },
    demoMeta: {
      displayName: "Atelier Vaucanson",
      handle: "vaucanson_geneve",
      bio: "Independent Haute Horlogerie Manufacture. Crafting 18 unique perpetual calendars and tourbillons annually by hand in Geneva.",
      location: "Geneva, Switzerland",
      email: "atelier@vaucanson-watches.ch",
      phone: "+41 22 731 4400",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-gh-1",
        type: "featured_link",
        position: 0,
        title: "Chronomètre Tourbillon No. 04 [Allocation Waitlist]",
        subtitle: "Hand-finished titanium cage with 72-hour power reserve",
        isVisible: true,
        isArchived: false,
        url: "https://vaucanson-watches.ch/tourbillon",
        badgeText: "1 OF 8 PIECES",
        highlightCoverUrl: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80",
        callToAction: "Request Collector Dossier",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 24. COPENHAGEN ARCHITECTURAL STUDIO
  {
    id: "tmpl_nordic_architect",
    name: "Copenhagen Architectural Studio",
    category: "Art Direction & Editorial",
    tagline: "Danish ash wood, minimalist chalk white and subtle fjord blue",
    description: "Nordic functional architecture with muted natural materials, expansive breathing room, and minimalist flat cards for architects and master planners.",
    badge: "MINIMAL",
    heroCoverUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "copenhagen_arch",
      name: "Copenhagen Minimal",
      palette: {
        background: "#F4F3F0",
        cardBackground: "#FFFFFF",
        primaryText: "#22252A",
        secondaryText: "#6E727A",
        accentGold: "#4B6B94",
        border: "#E2E0DA",
        buttonBackground: "#22252A",
        buttonText: "#F4F3F0",
      },
      typography: {
        headingFont: "Plus Jakarta Sans",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-xl",
        buttonStyle: "solid",
        buttonShadow: "none",
      },
      backgroundConfig: {
        type: "dot_grid",
        patternColor: "#4B6B94",
        patternOpacity: 0.45,
        particleSpeed: 0.7,
      },
    },
    cardDesign: {
      presetId: "minimal_flat",
      name: "Danish Ash Minimalist",
      borderRadius: "rounded-xl",
      borderStyle: "subtle",
      shadowStyle: "soft",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#4B6B94",
    },
    demoMeta: {
      displayName: "Sorensen & Dahl Arkitekter",
      handle: "sorensen_dahl",
      bio: "Scandinavian Architecture & Urban Ecology Practice. Designing carbon-neutral timber libraries, waterfront homes & pavilions.",
      location: "Copenhagen, Denmark",
      email: "tegnestue@sorensendahl.dk",
      phone: "+45 33 12 88 00",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-ca-1",
        type: "featured_link",
        position: 0,
        title: "Fjord Pavilion: Sustainable CLT Timber Architecture",
        subtitle: "Winner of the 2026 Mies Crown Hall Americas & Nordic Design Prize",
        isVisible: true,
        isArchived: false,
        url: "https://sorensendahl.dk/fjord-pavilion",
        badgeText: "PRIZE WINNER",
        highlightCoverUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        callToAction: "Explore Architectural Plans",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 25. MIAMI OCEAN DRIVE SYNTHWAVE
  {
    id: "tmpl_miami_vice_synth",
    name: "Miami Ocean Drive Synthwave",
    category: "Nightlife & Cyber Chic",
    tagline: "Midnight palm purple, electric flamingo pink and ocean turquoise",
    description: "Sun-drenched retro 80s synth aesthetic with electric pink neon glows, deep palm silhouettes, and animated neon horizon lines for music producers.",
    badge: "POPULAR",
    heroCoverUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "miami_synthwave",
      name: "Miami Synthwave",
      palette: {
        background: "#120824",
        cardBackground: "#1E0F38",
        primaryText: "#FFF0FA",
        secondaryText: "#F472B6",
        accentGold: "#14B8A6",
        border: "#3F1D6E",
        buttonBackground: "#F43F5E",
        buttonText: "#FFFFFF",
      },
      typography: {
        headingFont: "Syne",
        bodyFont: "Outfit",
      },
      geometry: {
        buttonRadius: "rounded-full",
        cardRadius: "rounded-3xl",
        buttonStyle: "pill",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "neon_horizon",
        patternColor: "#F43F5E",
        patternOpacity: 0.7,
        particleSpeed: 1.4,
      },
    },
    cardDesign: {
      presetId: "cyber_neon",
      name: "Miami Vice Neon Glow",
      borderRadius: "rounded-3xl",
      borderStyle: "glow",
      shadowStyle: "neon",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#F43F5E",
    },
    demoMeta: {
      displayName: "Sonny Vega",
      handle: "sonny_vega_synth",
      bio: "80s Outrun & Retrowave Sound Designer. Soundtrack composer for Cyberpunk & Netflix anime series • Analog synth collector.",
      location: "Miami Beach, Florida",
      email: "sonny@ocean-drive-music.com",
      phone: "+1 (305) 534-8800",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-mv-1",
        type: "featured_link",
        position: 0,
        title: "MIDNIGHT PALMS: Retrowave Cassette & Vinyl Drop",
        subtitle: "Limited neon pink dual-cassette tape and gatefold vinyl",
        isVisible: true,
        isArchived: false,
        url: "https://sonnyvega.bandcamp.com",
        badgeText: "LIMITED VINYL",
        highlightCoverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
        callToAction: "Order Vinyl Record",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 26. MAYFAIR PRIVATE MEMBERS CLUB
  {
    id: "tmpl_london_mayfair_club",
    name: "Mayfair Private Members Club",
    category: "Quiet Luxury & Heritage",
    tagline: "Chesterfield oxblood leather, antique brass and dark walnut warmth",
    description: "Centuries-old London club elegance with oxblood leather stitching, burnished brass accents, and Cormorant Garamond typography for private members clubs.",
    badge: "EXCLUSIVE",
    heroCoverUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "mayfair_club",
      name: "Mayfair Chesterfield",
      palette: {
        background: "#16070B",
        cardBackground: "#240E14",
        primaryText: "#FAF5F2",
        secondaryText: "#C49A8F",
        accentGold: "#CA8A04",
        border: "#421C26",
        buttonBackground: "#CA8A04",
        buttonText: "#16070B",
      },
      typography: {
        headingFont: "Cormorant Garamond",
        bodyFont: "Inter",
      },
      geometry: {
        buttonRadius: "rounded-lg",
        cardRadius: "rounded-xl",
        buttonStyle: "shadow_gold",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "subtle_noise",
        patternColor: "#CA8A04",
        patternOpacity: 0.5,
        particleSpeed: 0.6,
      },
    },
    cardDesign: {
      presetId: "leather_stitch",
      name: "Chesterfield Oxblood Stitch",
      borderRadius: "rounded-xl",
      borderStyle: "leather_stitch",
      shadowStyle: "soft",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#CA8A04",
    },
    demoMeta: {
      displayName: "The Carlton & Belgrave Club",
      handle: "carlton_belgrave_club",
      bio: "Private Members Society Founded in St. James's 1842. Curating private art collections, wine cellars, and reciprocal global access.",
      location: "St. James's, London SW1",
      email: "secretariat@carltonbelgrave.co.uk",
      phone: "+44 20 7930 4400",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-mc-1",
        type: "featured_link",
        position: 0,
        title: "2026 Annual Membership Proposal & Election",
        subtitle: "Sponsored nominations for the Michaelmas term admissions",
        isVisible: true,
        isArchived: false,
        url: "https://carltonbelgrave.co.uk/admissions",
        badgeText: "CONFIDENTIAL",
        highlightCoverUrl: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=800&q=80",
        callToAction: "Request Proposal Packet",
        accessRules: { isLocked: true, password: "MAYFAIR", barrier: "protected", scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 27. TIER-1 ESPORTS WORLD CHAMPION
  {
    id: "tmpl_esports_champion",
    name: "Tier-1 Esports World Champion",
    category: "Entertainment & Film",
    tagline: "Stealth matte carbon, apex predator red and championship gold",
    description: "Pro gaming pedigree featuring stealth dark carbon, aggressive angular brutalist borders, and crimson energy for competitive champions and streamers.",
    badge: "POPULAR",
    heroCoverUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "esports_apex",
      name: "Apex Esports Carbon",
      palette: {
        background: "#08090C",
        cardBackground: "#111318",
        primaryText: "#FFFFFF",
        secondaryText: "#7E8594",
        accentGold: "#EF4444",
        border: "#202430",
        buttonBackground: "#EF4444",
        buttonText: "#FFFFFF",
      },
      typography: {
        headingFont: "Space Grotesk",
        bodyFont: "JetBrains Mono",
      },
      geometry: {
        buttonRadius: "rounded-md",
        cardRadius: "rounded-xl",
        buttonStyle: "brutalist",
        buttonShadow: "hard_offset",
      },
      backgroundConfig: {
        type: "cyber_matrix",
        patternColor: "#EF4444",
        patternOpacity: 0.6,
        particleSpeed: 1.3,
      },
    },
    cardDesign: {
      presetId: "neo_brutalist",
      name: "Apex Champion Steel",
      borderRadius: "rounded-md",
      borderStyle: "brutalist_bold",
      shadowStyle: "hard_brutalist",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#EF4444",
    },
    demoMeta: {
      displayName: "Jax 'VORTEX' Chen",
      handle: "vortex_fps",
      bio: "3x World Champion FPS Pro Player & Red Bull Athlete. 2.4M on Twitch • Team Captain @ Apex Dynasty Esports.",
      location: "Seoul • Los Angeles",
      email: "management@vortextv.gg",
      phone: "+1 (424) 888-9011",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-ec-1",
        type: "featured_link",
        position: 0,
        title: "World Championship Finals Stream & Drops [Twitch]",
        subtitle: "Watch live with exclusive in-game weapon skins and player charms",
        isVisible: true,
        isArchived: false,
        url: "https://twitch.tv",
        badgeText: "LIVE ON TWITCH",
        highlightCoverUrl: "https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&w=800&q=80",
        callToAction: "Tune In Live",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 28. MARRAKECH RIAD & OASIS
  {
    id: "tmpl_marrakech_riad",
    name: "Marrakech Riad & Oasis",
    category: "Artisanal & Atelier",
    tagline: "Majorelle cobalt blue, terracotta zellige and saffron gold",
    description: "Vibrant Moroccan artisanal palace styling with intense Majorelle cobalt, warm terracotta tiles, and shimmering saffron accents for textile curators.",
    badge: "AVANT-GARDE",
    heroCoverUrl: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "marrakech_oasis",
      name: "Marrakech Majorelle",
      palette: {
        background: "#0C142E",
        cardBackground: "#14224A",
        primaryText: "#FFFDF7",
        secondaryText: "#E0B785",
        accentGold: "#EAB308",
        border: "#253875",
        buttonBackground: "#C86240",
        buttonText: "#FFFDF7",
      },
      typography: {
        headingFont: "Playfair Display",
        bodyFont: "Plus Jakarta Sans",
      },
      geometry: {
        buttonRadius: "rounded-2xl",
        cardRadius: "rounded-3xl",
        buttonStyle: "solid",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "canvas_aurora_waves",
        patternColor: "#EAB308",
        patternOpacity: 0.6,
        particleSpeed: 0.8,
      },
    },
    cardDesign: {
      presetId: "floating_elevation",
      name: "Majorelle Zellige Tile",
      borderRadius: "rounded-3xl",
      borderStyle: "glow",
      shadowStyle: "floating",
      surfaceStyle: "solid",
      hoverEffect: "lift",
      padding: "spacious",
      accentColor: "#EAB308",
    },
    demoMeta: {
      displayName: "Yasmine Benali",
      handle: "yasmine_riad_atelier",
      bio: "Textile & Ceramic Designer @ Medina Riad Atelier. Hand-knotted Berber rugs & botanical indigo ceramics crafted with Atlas artisan guilds.",
      location: "Marrakech, Medina",
      email: "contact@yasminebenali.ma",
      phone: "+212 524 388 900",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-mr-1",
        type: "featured_link",
        position: 0,
        title: "Atlas Mountain Hand-Knotted Wool Rug Collection",
        subtitle: "Each rug takes 4 months of hand-weaving by Berber women cooperatives",
        isVisible: true,
        isArchived: false,
        url: "https://yasminebenali.ma/rugs",
        badgeText: "HANDMADE CO-OP",
        highlightCoverUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80",
        callToAction: "Explore Rug Gallery",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 29. SPATIAL AI & NEURAL VISION
  {
    id: "tmpl_spatial_ai_vision",
    name: "Spatial AI & Neural Vision",
    category: "Tech & AI Founders",
    tagline: "Iridescent violet, holographic emerald and neural holographic foil",
    description: "Next-generation spatial intelligence and holographic neural interface styling with iridescent violet gradients and holographic foil card borders.",
    badge: "AVANT-GARDE",
    heroCoverUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "spatial_ai",
      name: "Spatial Hologram",
      palette: {
        background: "#0F071D",
        cardBackground: "#1A0E32",
        primaryText: "#F5F3FF",
        secondaryText: "#C4B5FD",
        accentGold: "#10B981",
        border: "#341B64",
        buttonBackground: "#8B5CF6",
        buttonText: "#FFFFFF",
      },
      typography: {
        headingFont: "Space Grotesk",
        bodyFont: "Plus Jakarta Sans",
      },
      geometry: {
        buttonRadius: "rounded-xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "gradient_luxe",
        buttonShadow: "colored_glow",
      },
      backgroundConfig: {
        type: "iridescent_hologram",
        patternColor: "#8B5CF6",
        patternOpacity: 0.7,
        particleSpeed: 1.1,
      },
    },
    cardDesign: {
      presetId: "holographic_foil",
      name: "Neural Holographic Foil",
      borderRadius: "rounded-2xl",
      borderStyle: "rainbow_prism",
      shadowStyle: "neon",
      surfaceStyle: "glass",
      hoverEffect: "lift",
      padding: "normal",
      accentColor: "#10B981",
    },
    demoMeta: {
      displayName: "Dr. Elena Rostova",
      handle: "elena_rostova_spatial",
      bio: "VP of Spatial AI @ OpticMatrix Labs. Leading foundation models for neural radiance fields (NeRF) and holographic AR headsets.",
      location: "San Francisco • Zurich",
      email: "elena@opticmatrix.ai",
      phone: "+1 (415) 790-3344",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-sa-1",
        type: "featured_link",
        position: 0,
        title: "OpticMatrix Spatial Engine: Real-Time 3D World Model",
        subtitle: "Photorealistic 60fps holographic reconstruction on mobile devices",
        isVisible: true,
        isArchived: false,
        url: "https://opticmatrix.ai/engine",
        badgeText: "SPATIAL SDK",
        highlightCoverUrl: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=800&q=80",
        callToAction: "Request Developer Beta",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },

  // 30. ASPEN ALPINE SKI & CHALET
  {
    id: "tmpl_aspen_chalet",
    name: "Aspen Alpine Ski & Chalet",
    category: "Quiet Luxury & Heritage",
    tagline: "Powder snow white, deep alpine pine and warm fireplace copper",
    description: "Exclusive winter retreat luxury pairing crisp powder snow, deep pine forest greens, copper fireplace warmth, and frosted glass cards for alpine clubs.",
    badge: "EXCLUSIVE",
    heroCoverUrl: "https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    theme: {
      id: "aspen_chalet",
      name: "Aspen Powder Pine",
      palette: {
        background: "#F8FAFC",
        cardBackground: "#FFFFFF",
        primaryText: "#0F172A",
        secondaryText: "#475569",
        accentGold: "#B45309",
        border: "#E2E8F0",
        buttonBackground: "#1E3A2F",
        buttonText: "#F8FAFC",
      },
      typography: {
        headingFont: "Cinzel",
        bodyFont: "Outfit",
      },
      geometry: {
        buttonRadius: "rounded-2xl",
        cardRadius: "rounded-2xl",
        buttonStyle: "solid",
        buttonShadow: "subtle",
      },
      backgroundConfig: {
        type: "floating_bubbles",
        patternColor: "#1E3A2F",
        patternOpacity: 0.45,
        particleSpeed: 0.6,
      },
    },
    cardDesign: {
      presetId: "cupertino_glass",
      name: "Alpine Frosted Ice",
      borderRadius: "rounded-2xl",
      borderStyle: "subtle",
      shadowStyle: "soft",
      surfaceStyle: "glass",
      hoverEffect: "lift",
      padding: "spacious",
      accentColor: "#B45309",
    },
    demoMeta: {
      displayName: "Christian von Berg",
      handle: "christian_aspen_ski",
      bio: "Private Heli-Ski Expeditioner & Alpine Chalet Concierge. Guiding backcountry lines across Aspen Highlands & St. Moritz.",
      location: "Aspen, Colorado • St. Moritz",
      email: "concierge@aspen-chaletclub.com",
      phone: "+1 (970) 925-1100",
      verified: true,
    },
    sampleBlocks: [
      {
        id: "b-ac-1",
        type: "featured_link",
        position: 0,
        title: "Highland Peak Heli-Skiing Expedition [Winter 2027]",
        subtitle: "Private A-Star helicopter charter with certified mountain guides",
        isVisible: true,
        isArchived: false,
        url: "https://aspen-chaletclub.com/heliski",
        badgeText: "PRIVATE HELI",
        highlightCoverUrl: "https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=800&q=80",
        callToAction: "Book Expedition",
        accessRules: { isLocked: false, scheduleEnabled: false },
        createdAt: "2026-09-01T00:00:00.000Z",
        updatedAt: "2026-09-01T00:00:00.000Z",
      },
    ],
  },
];
