import { AsoobiProfileDocument } from "@/types/builder";
import { DEFAULT_CARD_DESIGN } from "@/lib/cardDesigns";

export const INITIAL_PROFILE_DATA: AsoobiProfileDocument = {
  id: "profile-asoobi-demo",
  handle: "elena_vance",
  isVerified: true,
  status: "published",
  meta: {
    title: "Elena Vance",
    bio: "Digital Stylist & Luxury Creative Director. Curating aesthetics, high-fashion campaigns & editorial drops in Milan & Paris.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    avatarShape: "circle",
    heroCoverUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80",
    heroLayout: "grand_editorial",
    location: "Milan, Italy",
  },
  theme: {
    id: "asoobi_luxury_gold",
    name: "Asoobi Signature Gold",
    palette: {
      background: "#F9F9F7",
      cardBackground: "#FFFFFF",
      primaryText: "#1A1C20",
      secondaryText: "#918355",
      accentGold: "#D4AF37",
      border: "#E5E0D2",
      buttonBackground: "#D4AF37",
      buttonText: "#1A1C20",
    },
    typography: {
      headingFont: "Playfair Display",
      bodyFont: "Inter",
    },
    geometry: {
      buttonRadius: "rounded-xl",
      cardRadius: "rounded-2xl",
      buttonStyle: "shadow_gold",
      buttonShadow: "colored_glow",
    },
    backgroundConfig: {
      type: "canvas_constellation",
      patternColor: "#D4AF37",
      patternOpacity: 0.75,
      particleSpeed: 1,
    },
  },
  cardDesign: DEFAULT_CARD_DESIGN,
  blocks: [
    {
      id: "block-1",
      type: "featured_link",
      position: 0,
      title: "Fall/Winter Capsule Campaign '26",
      subtitle: "Exclusive lookbook and behind-the-scenes film",
      isVisible: true,
      isArchived: false,
      url: "https://asoobi.com/campaigns/fw26",
      badgeText: "NEW DROP",
      highlightCoverUrl: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=800&q=80",
      callToAction: "Explore Lookbook",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
    {
      id: "block-2",
      type: "standard_link",
      position: 1,
      title: "Vogue Italia Feature: The New Renaissance",
      subtitle: "Read the full 12-page interview",
      isVisible: true,
      isArchived: false,
      url: "https://vogue.it",
      icon: "Sparkles",
      thumbnailUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=200&q=80",
      openInNewTab: true,
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
    {
      id: "block-3",
      type: "collection",
      position: 2,
      title: "Curated Wardrobe Essentials",
      subtitle: "Handpicked luxury items with exclusive creator discounts",
      isVisible: true,
      isArchived: false,
      layout: "grid",
      accessRules: { isLocked: false, scheduleEnabled: false },
      items: [
        {
          id: "item-1",
          title: "Cashmere Overcoat",
          url: "https://asoobi.com/shop/overcoat",
          thumbnailUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80",
          price: "$890",
        },
        {
          id: "item-2",
          title: "Silk Jacquard Scarf",
          url: "https://asoobi.com/shop/scarf",
          thumbnailUrl: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=300&q=80",
          price: "$240",
        },
        {
          id: "item-3",
          title: "Handcrafted Loafers",
          url: "https://asoobi.com/shop/loafers",
          thumbnailUrl: "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?auto=format&fit=crop&w=300&q=80",
          price: "$520",
        },
      ],
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
    {
      id: "block-4",
      type: "standard_link",
      position: 3,
      title: "VIP Backstage Pass: Paris Couture",
      subtitle: "Private guestlist link (Password required)",
      isVisible: true,
      isArchived: false,
      url: "https://asoobi.com/vip/paris-couture",
      icon: "Lock",
      openInNewTab: true,
      accessRules: {
        isLocked: true,
        password: "ASOOBI_COUTURE",
        scheduleEnabled: false,
      },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
    {
      id: "block-5",
      type: "discount_code",
      position: 4,
      title: "Asoobi Private Atelier Code",
      subtitle: "Valid on all direct runway orders",
      isVisible: true,
      isArchived: false,
      code: "ELENA20",
      discountPercentageOrValue: "20% OFF",
      brandName: "Asoobi Luxury Marketplace",
      destinationUrl: "https://asoobi.com",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
    {
      id: "block-6",
      type: "contact_form",
      position: 5,
      title: "Commercial Inquiries & Representation",
      subtitle: "Direct line for brands, agencies, and styling commissions",
      isVisible: true,
      isArchived: false,
      targetEmail: "elena@vancestudio.com",
      fields: {
        collectName: true,
        collectPhone: false,
        collectNote: true,
      },
      successMessage: "Thank you for reaching out. Elena's team will reply within 24 hours.",
      submitButtonText: "Submit Inquiry",
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
    {
      id: "block-7",
      type: "social_icons",
      position: 6,
      title: "Official Social Accounts",
      isVisible: true,
      isArchived: false,
      iconStyle: "filled_gold",
      platformLinks: [
        { platform: "instagram", url: "https://instagram.com", position: 0 },
        { platform: "tiktok", url: "https://tiktok.com", position: 1 },
        { platform: "youtube", url: "https://youtube.com", position: 2 },
        { platform: "x", url: "https://x.com", position: 3 },
      ],
      accessRules: { isLocked: false, scheduleEnabled: false },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
  ],
};
