import { AsoobiProfileDocument } from "@/types/builder";

export interface ProfileTemplate {
  id: string;
  name: string;
  platform: "Instagram" | "LinkedIn" | "X (Twitter)" | "YouTube" | "TikTok" | "Luxury Atelier";
  tagline: string;
  description: string;
  badge: string;
  badgeColor: string;
  category: string;
  profileData: AsoobiProfileDocument;
}

export const REAL_PROFILE_TEMPLATES: ProfileTemplate[] = [
  {
    id: "tmpl-instagram-creator",
    name: "Instagram Lifestyle & Fashion Influencer",
    platform: "Instagram",
    tagline: "High-engagement aesthetic setup with LTK affiliate shop, presets & collab form",
    description: "The classic real-world Instagram bio link setup: featured outfit lookbook, curated shop collection with affiliate links, preset discount code, and brand partnership inquiry form.",
    badge: "Instagram",
    badgeColor: "bg-gradient-to-r from-pink-500 via-purple-500 to-amber-500 text-white",
    category: "Social Creators",
    profileData: {
      id: "profile-ig-creator",
      handle: "camille_styles",
      isVerified: true,
      status: "published",
      meta: {
        title: "Camille Laurent",
        bio: "Parisian style & daily moments 🥐✨ | Sharing seasonal wardrobe edits, skincare staples & studio vlogs. Co-founder @MaisonAura",
        avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
        avatarShape: "circle",
        heroCoverUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80",
        heroLayout: "grand_editorial",
        location: "Paris, France",
      },
      theme: {
        id: "ig_blush_gold",
        name: "Parisian Rose & Gold",
        palette: {
          background: "#FDFBF7",
          cardBackground: "#FFFFFF",
          primaryText: "#1F1B1A",
          secondaryText: "#A38F85",
          accentGold: "#D4AF37",
          border: "#EFE8E1",
          buttonBackground: "#1F1B1A",
          buttonText: "#FFFFFF",
        },
        typography: {
          headingFont: "Playfair Display",
          bodyFont: "Inter",
        },
        geometry: {
          buttonRadius: "rounded-2xl",
          cardRadius: "rounded-3xl",
          buttonStyle: "solid",
        },
      },
      blocks: [
        {
          id: "ig-block-1",
          type: "featured_link",
          position: 0,
          title: "Fall Capsule Lookbook 2026",
          subtitle: "Watch the full styling breakdown & shop all 15 key looks",
          isVisible: true,
          isArchived: false,
          url: "https://instagram.com",
          badgeText: "NEW EDIT",
          highlightCoverUrl: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=800&q=80",
          callToAction: "Explore Outfits",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "ig-block-2",
          type: "collection",
          position: 1,
          title: "My Daily Essentials (LTK & ShopMy)",
          subtitle: "Exact items I wear on my Instagram stories this week",
          isVisible: true,
          isArchived: false,
          layout: "grid",
          accessRules: { isLocked: false, scheduleEnabled: false },
          items: [
            {
              id: "item-ig-1",
              title: "Oversized Cashmere Knit",
              url: "https://instagram.com",
              price: "$290",
              thumbnailUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=300&q=80",
            },
            {
              id: "item-ig-2",
              title: "Vintage Leather Tote",
              url: "https://instagram.com",
              price: "$480",
              thumbnailUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=300&q=80",
            },
            {
              id: "item-ig-3",
              title: "Signature Gold Signet Ring",
              url: "https://instagram.com",
              price: "$145",
              thumbnailUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=300&q=80",
            },
          ],
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "ig-block-3",
          type: "discount_code",
          position: 2,
          title: "Lightroom Aesthetic Presets 2026",
          subtitle: "Get 25% off my 1-click Paris & Milan photo presets",
          isVisible: true,
          isArchived: false,
          code: "CAMILLE25",
          discountPercentageOrValue: "25% OFF",
          brandName: "Camille Preset Shop",
          destinationUrl: "https://instagram.com",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "ig-block-4",
          type: "contact_form",
          position: 3,
          title: "Brand Sponsorships & PR Inquiries",
          subtitle: "Direct line for agencies, press pulls, and brand partnerships",
          isVisible: true,
          isArchived: false,
          targetEmail: "collaborations@camillelaurent.com",
          fields: {
            collectName: true,
            collectPhone: false,
            collectNote: true,
          },
          customFields: [
            { id: "brand_name", label: "Brand Name", type: "text", placeholder: "e.g. Chanel / Celine / Jacquemus", required: true },
            { id: "deliverables", label: "Campaign Format", type: "select", options: ["Instagram Reel + 3 Stories", "Dedicated Photo Carousel", "YouTube Integration", "Long-term Ambassadorship"], required: true },
          ],
          successMessage: "Thank you! Camille's management agency will review your brief within 24 hours.",
          submitButtonText: "Submit Collaboration Pitch",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "ig-block-5",
          type: "social_icons",
          position: 4,
          title: "Connect Across Platforms",
          isVisible: true,
          isArchived: false,
          iconStyle: "filled_gold",
          platformLinks: [
            { platform: "instagram", url: "https://instagram.com", position: 0 },
            { platform: "tiktok", url: "https://tiktok.com", position: 1 },
            { platform: "youtube", url: "https://youtube.com", position: 2 },
            { platform: "email", url: "mailto:mgmt@camillelaurent.com", position: 3 },
          ],
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
      ],
    },
  },
  {
    id: "tmpl-linkedin-executive",
    name: "LinkedIn Executive & B2B Thought Leader",
    platform: "LinkedIn",
    tagline: "Authority layout for C-suite, keynote speakers & venture advisors",
    description: "Built for LinkedIn creators and business leaders: Harvard Business Review / Forbes press link, keynote booking form, gated 2026 market intelligence report, and executive newsletter signup.",
    badge: "LinkedIn",
    badgeColor: "bg-[#0077B5] text-white",
    category: "Professional & B2B",
    profileData: {
      id: "profile-linkedin-exec",
      handle: "marcus_vance",
      isVerified: true,
      status: "published",
      meta: {
        title: "Marcus Vance",
        bio: "Managing Partner @ApexVentures | Writing about AI infrastructure, enterprise scale & board governance. 120k+ readers on 'The High Output Memo'. Keynote Speaker.",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
        avatarShape: "rounded",
        heroCoverUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
        heroLayout: "grand_editorial",
        location: "New York, NY",
      },
      theme: {
        id: "linkedin_navy_slate",
        name: "Wall Street Slate & Navy",
        palette: {
          background: "#F5F7FA",
          cardBackground: "#FFFFFF",
          primaryText: "#0F172A",
          secondaryText: "#64748B",
          accentGold: "#0A66C2",
          border: "#E2E8F0",
          buttonBackground: "#0A66C2",
          buttonText: "#FFFFFF",
        },
        typography: {
          headingFont: "Inter",
          bodyFont: "Inter",
        },
        geometry: {
          buttonRadius: "rounded-xl",
          cardRadius: "rounded-2xl",
          buttonStyle: "solid",
        },
      },
      blocks: [
        {
          id: "li-block-1",
          type: "featured_link",
          position: 0,
          title: "Read in Forbes: The 2026 Enterprise AI Shift",
          subtitle: "Why 84% of Fortune 500 tech roadmaps are decoupling monolithic LLMs.",
          isVisible: true,
          isArchived: false,
          url: "https://forbes.com",
          badgeText: "FORBES FEATURE",
          highlightCoverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
          callToAction: "Read 8-Min Article",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "li-block-2",
          type: "standard_link",
          position: 1,
          title: "Executive Whitepaper: 2026 Boardroom AI Governance",
          subtitle: "Confidential executive briefing paper (Password: APEX2026)",
          isVisible: true,
          isArchived: false,
          url: "https://apexventures.com/research",
          icon: "Lock",
          openInNewTab: true,
          accessRules: {
            isLocked: true,
            password: "APEX2026",
            scheduleEnabled: false,
          },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "li-block-3",
          type: "contact_form",
          position: 2,
          title: "Keynote Speaking & Advisory Inquiries",
          subtitle: "Inquire for global summits, executive retreats & corporate keynotes",
          isVisible: true,
          isArchived: false,
          targetEmail: "speaking@marcusvance.com",
          fields: {
            collectName: true,
            collectPhone: true,
            collectNote: true,
          },
          customFields: [
            { id: "event_name", label: "Conference / Organization Name", type: "text", placeholder: "e.g. World Economic Forum / SaaStr", required: true },
            { id: "event_date", label: "Event Target Date", type: "date", required: true },
            { id: "format", label: "Format", type: "select", options: ["In-Person Keynote (45 min)", "Panel Fireside Chat", "Executive Offsite Workshop", "Virtual Global Townhall"], required: true },
          ],
          successMessage: "Inquiry received. Marcus's chief of staff will confirm availability within 24 hours.",
          submitButtonText: "Check Speaking Availability",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "li-block-4",
          type: "standard_link",
          position: 3,
          title: "Subscribe to 'The High Output Memo'",
          subtitle: "Weekly tactical frameworks for tech operators & founders. Free on Substack.",
          isVisible: true,
          isArchived: false,
          url: "https://substack.com",
          thumbnailUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=200&q=80",
          openInNewTab: true,
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "li-block-5",
          type: "social_icons",
          position: 4,
          title: "Executive Channels",
          isVisible: true,
          isArchived: false,
          iconStyle: "minimal",
          platformLinks: [
            { platform: "linkedin", url: "https://linkedin.com", position: 0 },
            { platform: "x", url: "https://x.com", position: 1 },
            { platform: "email", url: "mailto:marcus@apexventures.com", position: 2 },
          ],
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
      ],
    },
  },
  {
    id: "tmpl-x-founder",
    name: "X (Twitter) Tech Founder & Indie Hacker",
    platform: "X (Twitter)",
    tagline: "Obsidian dark mode builder profile with Product Hunt drop & early access",
    description: "The quintessential setup used by Silicon Valley builders, AI engineers, and indie hackers on X: Live demo link, GitHub / Discord communities, early access waitlist, and investor pitch form.",
    badge: "X / Twitter",
    badgeColor: "bg-black text-white border border-neutral-700",
    category: "Tech & Builders",
    profileData: {
      id: "profile-x-builder",
      handle: "alex_builds",
      isVerified: true,
      status: "published",
      meta: {
        title: "Alex Thorne ⚡",
        bio: "Building @HyperScaleAI (YC W26) • 0 to $80k MRR in 6 months in public • Writing about autonomous agents, Next.js & founder mental models. DMs open.",
        avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80",
        avatarShape: "squircle",
        heroCoverUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
        heroLayout: "grand_editorial",
        location: "San Francisco, CA",
      },
      theme: {
        id: "x_dark_obsidian",
        name: "Obsidian Matrix Dark",
        palette: {
          background: "#0A0A0C",
          cardBackground: "#141418",
          primaryText: "#EDEDED",
          secondaryText: "#888892",
          accentGold: "#00F0FF",
          border: "#26262E",
          buttonBackground: "#EDEDED",
          buttonText: "#0A0A0C",
        },
        typography: {
          headingFont: "Inter",
          bodyFont: "Inter",
        },
        geometry: {
          buttonRadius: "rounded-xl",
          cardRadius: "rounded-2xl",
          buttonStyle: "solid",
        },
      },
      blocks: [
        {
          id: "x-block-1",
          type: "featured_link",
          position: 0,
          title: "HyperScale 2.0 Launch on Product Hunt",
          subtitle: "We just launched our real-time AI code refactoring engine. Upvote & test live sandbox!",
          isVisible: true,
          isArchived: false,
          url: "https://producthunt.com",
          badgeText: "#1 PRODUCT OF THE DAY",
          highlightCoverUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
          callToAction: "Try Live Playground Free",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "x-block-2",
          type: "discount_code",
          position: 1,
          title: "Founder Community Lifetime Pass",
          subtitle: "Special 40% discount code for our X / Twitter followers only",
          isVisible: true,
          isArchived: false,
          code: "BUILDINPUBLIC",
          discountPercentageOrValue: "40% OFF",
          brandName: "HyperScale Pro Tier",
          destinationUrl: "https://hyperscale.ai",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "x-block-3",
          type: "standard_link",
          position: 2,
          title: "Join 14,000+ AI Builders on Discord",
          subtitle: "Direct feedback channel, open-source models, and daily changelog drops.",
          isVisible: true,
          isArchived: false,
          url: "https://discord.com",
          thumbnailUrl: "https://images.unsplash.com/photo-1614680376593-902f749f7ffc?auto=format&fit=crop&w=200&q=80",
          openInNewTab: true,
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "x-block-4",
          type: "contact_form",
          position: 3,
          title: "Angel Investment & Strategic Advisory Pitch",
          subtitle: "Currently opening our Seed extension round. Inquire for our investor deck.",
          isVisible: true,
          isArchived: false,
          targetEmail: "founders@hyperscale.ai",
          fields: {
            collectName: true,
            collectPhone: false,
            collectNote: true,
          },
          customFields: [
            { id: "fund_name", label: "Fund / Angel Name", type: "text", placeholder: "e.g. Andreessen / Sequoia / Scout", required: true },
            { id: "check_size", label: "Target Ticket Size", type: "select", options: ["$25k - $50k (Angel)", "$100k - $250k", "$500k+ (Lead / Syndicate)"], required: true },
          ],
          successMessage: "Deck request sent. Alex will reply with DocSend link within 12 hours.",
          submitButtonText: "Request Investor Deck",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "x-block-5",
          type: "social_icons",
          position: 4,
          title: "Socials & Repos",
          isVisible: true,
          isArchived: false,
          iconStyle: "monochrome",
          platformLinks: [
            { platform: "x", url: "https://x.com", position: 0 },
            { platform: "youtube", url: "https://youtube.com", position: 1 },
            { platform: "linkedin", url: "https://linkedin.com", position: 2 },
            { platform: "email", url: "mailto:alex@hyperscale.ai", position: 3 },
          ],
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
      ],
    },
  },
  {
    id: "tmpl-youtube-creator",
    name: "YouTube Filmmaker & Video Creator",
    platform: "YouTube",
    tagline: "Cinematic layout for YouTubers, gear reviews & video sponsors",
    description: "The high-conversion link page used by prominent YouTube creators: Latest 4K episode embed, 'My Camera Gear & Desk Setup' collection, sponsor pitch form, and member community.",
    badge: "YouTube",
    badgeColor: "bg-[#FF0000] text-white",
    category: "Media & Video",
    profileData: {
      id: "profile-yt-creator",
      handle: "kai_visuals",
      isVerified: true,
      status: "published",
      meta: {
        title: "Kai Sterling 🎬",
        bio: "Cinematographer & Tech Storyteller (850K Subs). Exploring cameras, minimalist desk setups & workflow engineering. New documentary every Sunday.",
        avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
        avatarShape: "circle",
        heroCoverUrl: "https://images.unsplash.com/photo-1518173946687-a4c8a383392e?auto=format&fit=crop&w=1200&q=80",
        heroLayout: "grand_editorial",
        location: "Tokyo & Vancouver",
      },
      theme: {
        id: "yt_studio_dark",
        name: "Studio Cinema Dark",
        palette: {
          background: "#121214",
          cardBackground: "#1A1A1E",
          primaryText: "#F0F0F5",
          secondaryText: "#9696A0",
          accentGold: "#E50914",
          border: "#2C2C34",
          buttonBackground: "#E50914",
          buttonText: "#FFFFFF",
        },
        typography: {
          headingFont: "Inter",
          bodyFont: "Inter",
        },
        geometry: {
          buttonRadius: "rounded-xl",
          cardRadius: "rounded-2xl",
          buttonStyle: "solid",
        },
      },
      blocks: [
        {
          id: "yt-block-1",
          type: "featured_link",
          position: 0,
          title: "New Film: Inside the Minimalist Tokyo Studio",
          subtitle: "Watch in 4K HDR: Behind the scenes of our bespoke acoustic workspace & color suite.",
          isVisible: true,
          isArchived: false,
          url: "https://youtube.com",
          badgeText: "PREMIERE",
          highlightCoverUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80",
          callToAction: "Watch on YouTube (18 min)",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "yt-block-2",
          type: "collection",
          position: 1,
          title: "My 2026 Camera Rig & Desk Gear",
          subtitle: "Every lens, monitor, and audio interface used to shoot our films",
          isVisible: true,
          isArchived: false,
          layout: "grid",
          accessRules: { isLocked: false, scheduleEnabled: false },
          items: [
            {
              id: "item-yt-1",
              title: "Sony FX3 Full-Frame Cinema",
              url: "https://youtube.com",
              price: "$3,899",
              thumbnailUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=300&q=80",
            },
            {
              id: "item-yt-2",
              title: "35mm T1.5 Cine Prime",
              url: "https://youtube.com",
              price: "$1,150",
              thumbnailUrl: "https://images.unsplash.com/photo-1617005082133-548c4dd27f35?auto=format&fit=crop&w=300&q=80",
            },
            {
              id: "item-yt-3",
              title: "Solid Walnut Desk Mat",
              url: "https://youtube.com",
              price: "$95",
              thumbnailUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=300&q=80",
            },
          ],
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "yt-block-3",
          type: "contact_form",
          position: 2,
          title: "Channel Sponsorships & Product Integrations",
          subtitle: "Dedicated 60-90s integrations, dedicated reviews, and long-term channel partnerships",
          isVisible: true,
          isArchived: false,
          targetEmail: "sponsors@kaisterling.com",
          fields: {
            collectName: true,
            collectPhone: false,
            collectNote: true,
          },
          customFields: [
            { id: "sponsor_brand", label: "Brand / Product Name", type: "text", placeholder: "e.g. Sony / Apple / Shure", required: true },
            { id: "slot_type", label: "Integration Tier", type: "select", options: ["Dedicated 60s Mid-Roll", "Integrated Video Title Sponsor", "3-Video Campaign Bundle", "Full Dedicated Review Video"], required: true },
          ],
          successMessage: "Thank you. Our channel production director will send our 2026 rate card and media kit.",
          submitButtonText: "Submit Sponsor Brief",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "yt-block-4",
          type: "social_icons",
          position: 3,
          title: "Channels",
          isVisible: true,
          isArchived: false,
          iconStyle: "minimal",
          platformLinks: [
            { platform: "youtube", url: "https://youtube.com", position: 0 },
            { platform: "x", url: "https://x.com", position: 1 },
            { platform: "instagram", url: "https://instagram.com", position: 2 },
            { platform: "email", url: "mailto:kai@kaisterling.com", position: 3 },
          ],
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
      ],
    },
  },
  {
    id: "tmpl-tiktok-ugc",
    name: "TikTok & UGC Content Creator",
    platform: "TikTok",
    tagline: "High-energy mobile layout with Amazon Storefront & Media Kit",
    description: "The high-conversion bio link format used by viral TikTok creators and UGC specialists: Viral video links, Amazon Storefront collection, UGC rate card request, and brand collaboration booking.",
    badge: "TikTok",
    badgeColor: "bg-black text-[#00F2FE] border border-[#FE2C55]",
    category: "Social Creators",
    profileData: {
      id: "profile-tiktok-ugc",
      handle: "mia_creates",
      isVerified: true,
      status: "published",
      meta: {
        title: "Mia Chen • UGC Creator",
        bio: "Beauty, Tech & Lifestyle UGC Specialist 💖 | 40M+ organic views generated for brands | Featured on Forbes 30u30 | DMs & PR: mia@chenmedia.co",
        avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
        avatarShape: "circle",
        heroCoverUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=80",
        heroLayout: "grand_editorial",
        location: "Los Angeles, CA",
      },
      theme: {
        id: "tiktok_vibrant_dark",
        name: "Electric Violet & Neon",
        palette: {
          background: "#0E0E12",
          cardBackground: "#181820",
          primaryText: "#FFFFFF",
          secondaryText: "#A0A0B0",
          accentGold: "#FE2C55",
          border: "#2E2E3C",
          buttonBackground: "#FE2C55",
          buttonText: "#FFFFFF",
        },
        typography: {
          headingFont: "Inter",
          bodyFont: "Inter",
        },
        geometry: {
          buttonRadius: "rounded-2xl",
          cardRadius: "rounded-3xl",
          buttonStyle: "solid",
        },
      },
      blocks: [
        {
          id: "tt-block-1",
          type: "featured_link",
          position: 0,
          title: "2026 UGC Media Kit & Portfolio",
          subtitle: "Case studies, retention graphs & viral commercial video examples.",
          isVisible: true,
          isArchived: false,
          url: "https://tiktok.com",
          badgeText: "PORTFOLIO",
          highlightCoverUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80",
          callToAction: "View 24 UGC Ad Examples",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "tt-block-2",
          type: "collection",
          position: 1,
          title: "My Viral TikTok Finds (Amazon Storefront)",
          subtitle: "All the viral home, skincare, and studio tech from my recent videos",
          isVisible: true,
          isArchived: false,
          layout: "grid",
          accessRules: { isLocked: false, scheduleEnabled: false },
          items: [
            {
              id: "item-tt-1",
              title: "RGB Sunset Aura Lamp",
              url: "https://amazon.com",
              price: "$34",
              thumbnailUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=300&q=80",
            },
            {
              id: "item-tt-2",
              title: "Wireless Lavalier Mic Pro",
              url: "https://amazon.com",
              price: "$79",
              thumbnailUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=300&q=80",
            },
            {
              id: "item-tt-3",
              title: "Hydra Glass Skin Serum",
              url: "https://amazon.com",
              price: "$28",
              thumbnailUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=300&q=80",
            },
          ],
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "tt-block-3",
          type: "contact_form",
          position: 2,
          title: "Book UGC Video Package",
          subtitle: "Fast 48-hour turnarounds for high-converting TikTok Ad hooks & organic UGC",
          isVisible: true,
          isArchived: false,
          targetEmail: "booking@chenmedia.co",
          fields: {
            collectName: true,
            collectPhone: false,
            collectNote: true,
          },
          customFields: [
            { id: "brand_handle", label: "Brand Handle / URL", type: "text", placeholder: "@brandname on TikTok", required: true },
            { id: "package_type", label: "Desired Video Package", type: "select", options: ["3x UGC Ad Hooks Bundle", "5x UGC TikTok Variations", "Spark Ads Whitelisting Rights", "Monthly Retainer (10 videos)"], required: true },
          ],
          successMessage: "Thanks! Mia will send contract, onboarding link & product shipping address.",
          submitButtonText: "Request UGC Rate Card",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "tt-block-4",
          type: "social_icons",
          position: 3,
          title: "Follow Everywhere",
          isVisible: true,
          isArchived: false,
          iconStyle: "filled_gold",
          platformLinks: [
            { platform: "tiktok", url: "https://tiktok.com", position: 0 },
            { platform: "instagram", url: "https://instagram.com", position: 1 },
            { platform: "youtube", url: "https://youtube.com", position: 2 },
            { platform: "email", url: "mailto:mia@chenmedia.co", position: 3 },
          ],
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
      ],
    },
  },
  {
    id: "tmpl-luxury-atelier",
    name: "Luxury Atelier & High Jewelry House",
    platform: "Luxury Atelier",
    tagline: "Signature Gold high-fashion lookbook, password-gated VIP trunk show & concierge",
    description: "Designed for haute couture brands, fine jewelry ateliers, and luxury houses: Private showroom invitation, archival runway catalog, password-locked salon appointments, and concierge inquiry line.",
    badge: "Luxury Atelier",
    badgeColor: "bg-[#D4AF37] text-[#1A1C20] font-bold",
    category: "Luxury & Fashion",
    profileData: {
      id: "profile-luxury-atelier",
      handle: "maison_solenne",
      isVerified: true,
      status: "published",
      meta: {
        title: "Maison Solenne",
        bio: "Haute Joaillerie & Bespoke Timepieces. Handcrafted in Place Vendôme, Paris. By private appointment only.",
        avatarUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=400&q=80",
        avatarShape: "circle",
        heroCoverUrl: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1200&q=80",
        heroLayout: "grand_editorial",
        location: "Place Vendôme, Paris",
      },
      theme: {
        id: "asoobi_luxury_gold",
        name: "Asoobi Signature Gold",
        palette: {
          background: "#F9F9F7",
          cardBackground: "#FFFFFF",
          primaryText: "#1A1C20",
          secondaryText: "#918355",
          accentGold: "#D4AF37",
          border: "#E5E0D2",
          buttonBackground: "#D4AF37",
          buttonText: "#1A1C20",
        },
        typography: {
          headingFont: "Playfair Display",
          bodyFont: "Inter",
        },
        geometry: {
          buttonRadius: "rounded-xl",
          cardRadius: "rounded-2xl",
          buttonStyle: "shadow_gold",
        },
      },
      blocks: [
        {
          id: "lux-block-1",
          type: "featured_link",
          position: 0,
          title: "The 2026 High Jewelry Solstice Collection",
          subtitle: "Explore rare emeralds, fancy yellow diamonds & archival platinum settings.",
          isVisible: true,
          isArchived: false,
          url: "https://asoobi.com",
          badgeText: "NEW ARCHIVE",
          highlightCoverUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
          callToAction: "View Archival Lookbook",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "lux-block-2",
          type: "standard_link",
          position: 1,
          title: "VIP Backstage Salon Pass (Paris Haute Couture)",
          subtitle: "Private salon guestlist link (Password required)",
          isVisible: true,
          isArchived: false,
          url: "https://asoobi.com/vip/salon",
          icon: "Lock",
          openInNewTab: true,
          accessRules: {
            isLocked: true,
            password: "VENDOME_VIP",
            scheduleEnabled: false,
          },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "lux-block-3",
          type: "collection",
          position: 2,
          title: "Iconic Signature Pieces",
          subtitle: "Exemplary creations available for private acquisition",
          isVisible: true,
          isArchived: false,
          layout: "grid",
          accessRules: { isLocked: false, scheduleEnabled: false },
          items: [
            {
              id: "item-lux-1",
              title: "Solstice Emerald Collier",
              url: "https://asoobi.com",
              price: "Price Upon Request",
              thumbnailUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=300&q=80",
            },
            {
              id: "item-lux-2",
              title: "Vendôme Tourbillon Watch",
              url: "https://asoobi.com",
              price: "$68,000",
              thumbnailUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=300&q=80",
            },
            {
              id: "item-lux-3",
              title: "Celestial Diamond Cuff",
              url: "https://asoobi.com",
              price: "$24,500",
              thumbnailUrl: "https://images.unsplash.com/photo-1611591475836-8a9d16b5a374?auto=format&fit=crop&w=300&q=80",
            },
          ],
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "lux-block-4",
          type: "contact_form",
          position: 3,
          title: "Private Salon Appointment & Commissions",
          subtitle: "Book a confidential consultation at our Paris atelier or private global suite",
          isVisible: true,
          isArchived: false,
          targetEmail: "concierge@maisonsolenne.com",
          fields: {
            collectName: true,
            collectPhone: true,
            collectNote: true,
          },
          customFields: [
            { id: "city_suite", label: "Preferred Atelier Location", type: "select", options: ["Place Vendôme (Paris)", "Bond Street (London)", "Ginza (Tokyo)", "Fifth Avenue (New York)", "Private Flying Concierge"], required: true },
            { id: "bespoke_intent", label: "Acquisition Interest", type: "select", options: ["Custom Bespoke Commission", "Private Collection Viewing", "Archival Piece Restoration", "Red Carpet Loan Inquiries"], required: true },
          ],
          successMessage: "Thank you. Our private client liaison will arrange your salon appointment directly.",
          submitButtonText: "Request Private Appointment",
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
        {
          id: "lux-block-5",
          type: "social_icons",
          position: 4,
          title: "Official Channels",
          isVisible: true,
          isArchived: false,
          iconStyle: "filled_gold",
          platformLinks: [
            { platform: "instagram", url: "https://instagram.com", position: 0 },
            { platform: "x", url: "https://x.com", position: 1 },
            { platform: "email", url: "mailto:concierge@maisonsolenne.com", position: 2 },
          ],
          accessRules: { isLocked: false, scheduleEnabled: false },
          createdAt: "2026-09-01T00:00:00.000Z",
          updatedAt: "2026-09-01T00:00:00.000Z",
        },
      ],
    },
  },
];
